# Auto-generated body-color profiles for Tier-4 detection
# Generated by tools/build_sprite_db.py
#
# Format per entry:
#   "species": {
#       "shiny": {"lower": [H, S, V], "upper": [H, S, V]},
#       "normal": {"lower": [H, S, V], "upper": [H, S, V]},
#       "confirm_threshold": <int>,  # min pixels to confirm
#   }

POKEMON_BODY_COLORS = {
    "bulbasaur": {  # #001 hue_diff=53
        "shiny": {"lower": [32, 40, 80], "upper": [65, 255, 255]},
        "normal": {"lower": [72, 40, 80], "upper": [99, 255, 255]},
        "confirm_threshold": 185,
    },
    "ivysaur": {  # #002 hue_diff=55
        "shiny": {"lower": [19, 40, 80], "upper": [51, 255, 255]},
        "normal": {"lower": [79, 40, 80], "upper": [99, 255, 255]},
        "confirm_threshold": 262,
    },
    "venusaur": {  # #003 hue_diff=40
        "shiny": {"lower": [10, 40, 80], "upper": [60, 255, 255]},
        "normal": {"lower": [50, 40, 80], "upper": [80, 255, 255]},
        "confirm_threshold": 488,
    },
    "charmander": {  # #004 hue_diff=22
        "shiny": {"lower": [6, 40, 80], "upper": [34, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [24, 255, 255]},
        "confirm_threshold": 170,
    },
    "charmeleon": {  # #005 hue_diff=20
        "shiny": {"lower": [0, 40, 80], "upper": [32, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [23, 255, 255]},
        "confirm_threshold": 260,
    },
    "charizard": {  # #006 hue_diff=84
        "shiny": {"lower": [78, 40, 80], "upper": [95, 255, 255]},
        "normal": {"lower": [1, 40, 80], "upper": [27, 255, 255]},
        "confirm_threshold": 500,
    },
    "squirtle": {  # #007 hue_diff=14
        "shiny": {"lower": [89, 40, 80], "upper": [108, 255, 255]},
        "normal": {"lower": [92, 40, 80], "upper": [113, 255, 255]},
        "confirm_threshold": 148,
    },
    "wartortle": {  # #008 hue_diff=13
        "shiny": {"lower": [127, 40, 80], "upper": [143, 255, 255]},
        "normal": {"lower": [120, 40, 80], "upper": [135, 255, 255]},
        "confirm_threshold": 283,
    },
    "blastoise": {  # #009 hue_diff=28
        "shiny": {"lower": [115, 40, 80], "upper": [138, 255, 255]},
        "normal": {"lower": [92, 40, 80], "upper": [116, 255, 255]},
        "confirm_threshold": 371,
    },
    "caterpie": {  # #010 hue_diff=24
        "shiny": {"lower": [6, 40, 80], "upper": [37, 255, 255]},
        "normal": {"lower": [23, 40, 80], "upper": [52, 255, 255]},
        "confirm_threshold": 115,
    },
    "metapod": {  # #011 hue_diff=39
        "shiny": {"lower": [0, 40, 80], "upper": [20, 255, 255]},
        "normal": {"lower": [34, 40, 80], "upper": [49, 255, 255]},
        "confirm_threshold": 127,
    },
    "butterfree": {  # #012 hue_diff=30
        "shiny": {"lower": [127, 40, 80], "upper": [155, 255, 255]},
        "normal": {"lower": [115, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 243,
    },
    "kakuna": {  # #014 hue_diff=9
        "shiny": {"lower": [28, 40, 80], "upper": [44, 255, 255]},
        "normal": {"lower": [18, 40, 80], "upper": [31, 255, 255]},
        "confirm_threshold": 121,
    },
    "pidgeotto": {  # #017 hue_diff=13
        "shiny": {"lower": [16, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 269,
    },
    "rattata": {  # #019 hue_diff=60
        "shiny": {"lower": [19, 40, 80], "upper": [31, 255, 255]},
        "normal": {"lower": [139, 40, 80], "upper": [165, 255, 255]},
        "confirm_threshold": 98,
    },
    "raticate": {  # #020 hue_diff=10
        "shiny": {"lower": [3, 40, 80], "upper": [16, 255, 255]},
        "normal": {"lower": [3, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 247,
    },
    "fearow": {  # #022 hue_diff=8
        "shiny": {"lower": [14, 40, 80], "upper": [33, 255, 255]},
        "normal": {"lower": [6, 40, 80], "upper": [25, 255, 255]},
        "confirm_threshold": 406,
    },
    "ekans": {  # #023 hue_diff=47
        "shiny": {"lower": [13, 40, 80], "upper": [31, 255, 255]},
        "normal": {"lower": [152, 40, 80], "upper": [168, 255, 255]},
        "confirm_threshold": 185,
    },
    "arbok": {  # #024 hue_diff=40
        "shiny": {"lower": [13, 40, 80], "upper": [27, 255, 255]},
        "normal": {"lower": [151, 40, 80], "upper": [168, 255, 255]},
        "confirm_threshold": 404,
    },
    "sandshrew": {  # #027 hue_diff=10
        "shiny": {"lower": [27, 40, 80], "upper": [43, 255, 255]},
        "normal": {"lower": [10, 40, 80], "upper": [34, 255, 255]},
        "confirm_threshold": 138,
    },
    "nidoran_f": {  # #029 hue_diff=41
        "shiny": {"lower": [132, 40, 80], "upper": [142, 255, 255]},
        "normal": {"lower": [76, 40, 80], "upper": [109, 255, 255]},
        "confirm_threshold": 151,
    },
    "nidorina": {  # #030 hue_diff=58
        "shiny": {"lower": [149, 40, 80], "upper": [172, 255, 255]},
        "normal": {"lower": [89, 40, 80], "upper": [114, 255, 255]},
        "confirm_threshold": 234,
    },
    "nidoqueen": {  # #031 hue_diff=79
        "shiny": {"lower": [21, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [89, 40, 80], "upper": [110, 255, 255]},
        "confirm_threshold": 361,
    },
    "nidoran_m": {  # #032 hue_diff=42
        "shiny": {"lower": [97, 40, 80], "upper": [117, 255, 255]},
        "normal": {"lower": [139, 40, 80], "upper": [162, 255, 255]},
        "confirm_threshold": 170,
    },
    "nidorino": {  # #033 hue_diff=35
        "shiny": {"lower": [97, 40, 80], "upper": [117, 255, 255]},
        "normal": {"lower": [136, 40, 80], "upper": [162, 255, 255]},
        "confirm_threshold": 273,
    },
    "nidoking": {  # #034 hue_diff=46
        "shiny": {"lower": [94, 40, 80], "upper": [115, 255, 255]},
        "normal": {"lower": [138, 40, 80], "upper": [158, 255, 255]},
        "confirm_threshold": 442,
    },
    "clefairy": {  # #035 hue_diff=33
        "shiny": {"lower": [153, 40, 80], "upper": [163, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [16, 255, 255]},
        "confirm_threshold": 194,
    },
    "clefable": {  # #036 hue_diff=22
        "shiny": {"lower": [153, 40, 80], "upper": [163, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [12, 255, 255]},
        "confirm_threshold": 293,
    },
    "vulpix": {  # #037 hue_diff=19
        "shiny": {"lower": [18, 40, 80], "upper": [34, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [21, 255, 255]},
        "confirm_threshold": 218,
    },
    "ninetales": {  # #038 hue_diff=32
        "shiny": {"lower": [3, 40, 80], "upper": [175, 255, 255]},
        "normal": {"lower": [11, 40, 80], "upper": [31, 255, 255]},
        "confirm_threshold": 259,
    },
    "jigglypuff": {  # #039 hue_diff=15
        "shiny": {"lower": [154, 40, 80], "upper": [170, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [9, 255, 255]},
        "confirm_threshold": 168,
    },
    "wigglytuff": {  # #040 hue_diff=20
        "shiny": {"lower": [145, 40, 80], "upper": [165, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [14, 255, 255]},
        "confirm_threshold": 199,
    },
    "zubat": {  # #041 hue_diff=66
        "shiny": {"lower": [37, 40, 80], "upper": [52, 255, 255]},
        "normal": {"lower": [103, 40, 80], "upper": [129, 255, 255]},
        "confirm_threshold": 174,
    },
    "golbat": {  # #042 hue_diff=27
        "shiny": {"lower": [0, 40, 80], "upper": [8, 255, 255]},
        "normal": {"lower": [150, 40, 80], "upper": [163, 255, 255]},
        "confirm_threshold": 263,
    },
    "gloom": {  # #044 hue_diff=76
        "shiny": {"lower": [10, 40, 80], "upper": [39, 255, 255]},
        "normal": {"lower": [98, 40, 80], "upper": [119, 255, 255]},
        "confirm_threshold": 234,
    },
    "vileplume": {  # #045 hue_diff=20
        "shiny": {"lower": [8, 40, 80], "upper": [31, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "confirm_threshold": 307,
    },
    "parasect": {  # #047 hue_diff=18
        "shiny": {"lower": [10, 40, 80], "upper": [34, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "confirm_threshold": 296,
    },
    "venomoth": {  # #049 hue_diff=40
        "shiny": {"lower": [98, 40, 80], "upper": [115, 255, 255]},
        "normal": {"lower": [130, 40, 80], "upper": [150, 255, 255]},
        "confirm_threshold": 351,
    },
    "diglett": {  # #050 hue_diff=13
        "shiny": {"lower": [8, 40, 80], "upper": [31, 255, 255]},
        "normal": {"lower": [3, 40, 80], "upper": [31, 255, 255]},
        "confirm_threshold": 113,
    },
    "psyduck": {  # #054 hue_diff=70
        "shiny": {"lower": [85, 40, 80], "upper": [98, 255, 255]},
        "normal": {"lower": [12, 40, 80], "upper": [28, 255, 255]},
        "confirm_threshold": 198,
    },
    "golduck": {  # #055 hue_diff=17
        "shiny": {"lower": [96, 40, 80], "upper": [111, 255, 255]},
        "normal": {"lower": [98, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 287,
    },
    "mankey": {  # #056 hue_diff=17
        "shiny": {"lower": [13, 40, 80], "upper": [41, 255, 255]},
        "normal": {"lower": [7, 40, 80], "upper": [30, 255, 255]},
        "confirm_threshold": 172,
    },
    "poliwag": {  # #060 hue_diff=13
        "shiny": {"lower": [96, 40, 80], "upper": [109, 255, 255]},
        "normal": {"lower": [103, 40, 80], "upper": [121, 255, 255]},
        "confirm_threshold": 87,
    },
    "poliwhirl": {  # #061 hue_diff=16
        "shiny": {"lower": [93, 40, 80], "upper": [108, 255, 255]},
        "normal": {"lower": [104, 40, 80], "upper": [120, 255, 255]},
        "confirm_threshold": 119,
    },
    "poliwrath": {  # #062 hue_diff=58
        "shiny": {"lower": [46, 40, 80], "upper": [56, 255, 255]},
        "normal": {"lower": [97, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 149,
    },
    "machop": {  # #066 hue_diff=47
        "shiny": {"lower": [18, 40, 80], "upper": [37, 255, 255]},
        "normal": {"lower": [63, 40, 80], "upper": [75, 255, 255]},
        "confirm_threshold": 160,
    },
    "machoke": {  # #067 hue_diff=89
        "shiny": {"lower": [27, 40, 80], "upper": [39, 255, 255]},
        "normal": {"lower": [115, 40, 80], "upper": [133, 255, 255]},
        "confirm_threshold": 311,
    },
    "machamp": {  # #068 hue_diff=28
        "shiny": {"lower": [27, 40, 80], "upper": [43, 255, 255]},
        "normal": {"lower": [55, 40, 80], "upper": [73, 255, 255]},
        "confirm_threshold": 454,
    },
    "bellsprout": {  # #069 hue_diff=20
        "shiny": {"lower": [13, 40, 80], "upper": [44, 255, 255]},
        "normal": {"lower": [21, 40, 80], "upper": [49, 255, 255]},
        "confirm_threshold": 123,
    },
    "weepinbell": {  # #070 hue_diff=8
        "shiny": {"lower": [25, 40, 80], "upper": [44, 255, 255]},
        "normal": {"lower": [34, 40, 80], "upper": [49, 255, 255]},
        "confirm_threshold": 224,
    },
    "victreebel": {  # #071 hue_diff=20
        "shiny": {"lower": [13, 40, 80], "upper": [40, 255, 255]},
        "normal": {"lower": [34, 40, 80], "upper": [49, 255, 255]},
        "confirm_threshold": 328,
    },
    "tentacool": {  # #072 hue_diff=18
        "shiny": {"lower": [115, 40, 80], "upper": [125, 255, 255]},
        "normal": {"lower": [80, 40, 80], "upper": [110, 255, 255]},
        "confirm_threshold": 147,
    },
    "tentacruel": {  # #073 hue_diff=73
        "shiny": {"lower": [98, 40, 80], "upper": [108, 255, 255]},
        "normal": {"lower": [18, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 387,
    },
    "geodude": {  # #074 hue_diff=10
        "shiny": {"lower": [13, 40, 80], "upper": [28, 255, 255]},
        "normal": {"lower": [28, 40, 80], "upper": [41, 255, 255]},
        "confirm_threshold": 138,
    },
    "graveler": {  # #075 hue_diff=20
        "shiny": {"lower": [4, 40, 80], "upper": [25, 255, 255]},
        "normal": {"lower": [21, 40, 80], "upper": [45, 255, 255]},
        "confirm_threshold": 338,
    },
    "golem": {  # #076 hue_diff=18
        "shiny": {"lower": [5, 40, 80], "upper": [20, 255, 255]},
        "normal": {"lower": [17, 40, 80], "upper": [44, 255, 255]},
        "confirm_threshold": 328,
    },
    "rapidash": {  # #078 hue_diff=79
        "shiny": {"lower": [108, 40, 80], "upper": [118, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [32, 255, 255]},
        "confirm_threshold": 492,
    },
    "slowbro": {  # #080 hue_diff=63
        "shiny": {"lower": [119, 40, 80], "upper": [137, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [28, 255, 255]},
        "confirm_threshold": 418,
    },
    "magnemite": {  # #081 hue_diff=30
        "shiny": {"lower": [25, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [5, 255, 255]},
        "confirm_threshold": 52,
    },
    "magneton": {  # #082 hue_diff=18
        "shiny": {"lower": [0, 40, 80], "upper": [23, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "confirm_threshold": 132,
    },
    "farfetchd": {  # #083 hue_diff=27
        "shiny": {"lower": [0, 40, 80], "upper": [23, 255, 255]},
        "normal": {"lower": [10, 40, 80], "upper": [51, 255, 255]},
        "confirm_threshold": 218,
    },
    "doduo": {  # #084 hue_diff=16
        "shiny": {"lower": [18, 40, 80], "upper": [38, 255, 255]},
        "normal": {"lower": [7, 40, 80], "upper": [31, 255, 255]},
        "confirm_threshold": 149,
    },
    "dodrio": {  # #085 hue_diff=17
        "shiny": {"lower": [16, 40, 80], "upper": [38, 255, 255]},
        "normal": {"lower": [10, 40, 80], "upper": [28, 255, 255]},
        "confirm_threshold": 272,
    },
    "seel": {  # #086 hue_diff=80
        "shiny": {"lower": [1, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [115, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 50,
    },
    "dewgong": {  # #087 hue_diff=86
        "shiny": {"lower": [15, 40, 80], "upper": [25, 255, 255]},
        "normal": {"lower": [108, 40, 80], "upper": [119, 255, 255]},
        "confirm_threshold": 85,
    },
    "grimer": {  # #088 hue_diff=78
        "shiny": {"lower": [38, 40, 80], "upper": [50, 255, 255]},
        "normal": {"lower": [134, 40, 80], "upper": [167, 255, 255]},
        "confirm_threshold": 230,
    },
    "muk": {  # #089 hue_diff=66
        "shiny": {"lower": [43, 40, 80], "upper": [53, 255, 255]},
        "normal": {"lower": [140, 40, 80], "upper": [167, 255, 255]},
        "confirm_threshold": 319,
    },
    "shellder": {  # #090 hue_diff=84
        "shiny": {"lower": [2, 40, 80], "upper": [23, 255, 255]},
        "normal": {"lower": [105, 40, 80], "upper": [115, 255, 255]},
        "confirm_threshold": 115,
    },
    "cloyster": {  # #091 hue_diff=38
        "shiny": {"lower": [100, 40, 80], "upper": [111, 255, 255]},
        "normal": {"lower": [136, 40, 80], "upper": [150, 255, 255]},
        "confirm_threshold": 242,
    },
    "gastly": {  # #092 hue_diff=56
        "shiny": {"lower": [95, 40, 80], "upper": [105, 255, 255]},
        "normal": {"lower": [139, 40, 80], "upper": [161, 255, 255]},
        "confirm_threshold": 381,
    },
    "haunter": {  # #093 hue_diff=10
        "shiny": {"lower": [132, 40, 80], "upper": [152, 255, 255]},
        "normal": {"lower": [125, 40, 80], "upper": [145, 255, 255]},
        "confirm_threshold": 322,
    },
    "gengar": {  # #094 hue_diff=45
        "shiny": {"lower": [115, 40, 80], "upper": [125, 255, 255]},
        "normal": {"lower": [145, 40, 80], "upper": [170, 255, 255]},
        "confirm_threshold": 313,
    },
    "onix": {  # #095 hue_diff=10
        "shiny": {"lower": [25, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [35, 40, 80], "upper": [45, 255, 255]},
        "confirm_threshold": 421,
    },
    "drowzee": {  # #096 hue_diff=37
        "shiny": {"lower": [3, 40, 80], "upper": [179, 255, 255]},
        "normal": {"lower": [10, 40, 80], "upper": [30, 255, 255]},
        "confirm_threshold": 302,
    },
    "hypno": {  # #097 hue_diff=33
        "shiny": {"lower": [0, 40, 80], "upper": [175, 255, 255]},
        "normal": {"lower": [14, 40, 80], "upper": [30, 255, 255]},
        "confirm_threshold": 292,
    },
    "kingler": {  # #099 hue_diff=24
        "shiny": {"lower": [23, 40, 80], "upper": [45, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [26, 255, 255]},
        "confirm_threshold": 393,
    },
    "voltorb": {  # #100 hue_diff=65
        "shiny": {"lower": [110, 40, 80], "upper": [125, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [14, 255, 255]},
        "confirm_threshold": 89,
    },
    "electrode": {  # #101 hue_diff=86
        "shiny": {"lower": [97, 40, 80], "upper": [125, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [14, 255, 255]},
        "confirm_threshold": 72,
    },
    "exeggcute": {  # #102 hue_diff=20
        "shiny": {"lower": [13, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [2, 40, 80], "upper": [18, 255, 255]},
        "confirm_threshold": 304,
    },
    "exeggutor": {  # #103 hue_diff=21
        "shiny": {"lower": [6, 40, 80], "upper": [28, 255, 255]},
        "normal": {"lower": [34, 40, 80], "upper": [49, 255, 255]},
        "confirm_threshold": 343,
    },
    "marowak": {  # #105 hue_diff=16
        "shiny": {"lower": [8, 40, 80], "upper": [38, 255, 255]},
        "normal": {"lower": [8, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 200,
    },
    "hitmonlee": {  # #106 hue_diff=19
        "shiny": {"lower": [10, 40, 80], "upper": [41, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 274,
    },
    "lickitung": {  # #108 hue_diff=17
        "shiny": {"lower": [16, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [31, 255, 255]},
        "confirm_threshold": 409,
    },
    "koffing": {  # #109 hue_diff=66
        "shiny": {"lower": [76, 40, 80], "upper": [95, 255, 255]},
        "normal": {"lower": [19, 40, 80], "upper": [33, 255, 255]},
        "confirm_threshold": 247,
    },
    "weezing": {  # #110 hue_diff=77
        "shiny": {"lower": [80, 40, 80], "upper": [95, 255, 255]},
        "normal": {"lower": [162, 40, 80], "upper": [174, 255, 255]},
        "confirm_threshold": 474,
    },
    "rhyhorn": {  # #111 hue_diff=69
        "shiny": {"lower": [2, 40, 80], "upper": [14, 255, 255]},
        "normal": {"lower": [115, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 354,
    },
    "chansey": {  # #113 hue_diff=20
        "shiny": {"lower": [13, 40, 80], "upper": [26, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [178, 255, 255]},
        "confirm_threshold": 330,
    },
    "tangela": {  # #114 hue_diff=51
        "shiny": {"lower": [43, 40, 80], "upper": [65, 255, 255]},
        "normal": {"lower": [94, 40, 80], "upper": [105, 255, 255]},
        "confirm_threshold": 267,
    },
    "kangaskhan": {  # #115 hue_diff=15
        "shiny": {"lower": [16, 40, 80], "upper": [42, 255, 255]},
        "normal": {"lower": [6, 40, 80], "upper": [33, 255, 255]},
        "confirm_threshold": 430,
    },
    "horsea": {  # #116 hue_diff=17
        "shiny": {"lower": [88, 40, 80], "upper": [99, 255, 255]},
        "normal": {"lower": [97, 40, 80], "upper": [115, 255, 255]},
        "confirm_threshold": 137,
    },
    "goldeen": {  # #118 hue_diff=8
        "shiny": {"lower": [3, 40, 80], "upper": [31, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [22, 255, 255]},
        "confirm_threshold": 80,
    },
    "seaking": {  # #119 hue_diff=30
        "shiny": {"lower": [16, 40, 80], "upper": [44, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [14, 255, 255]},
        "confirm_threshold": 288,
    },
    "staryu": {  # #120 hue_diff=13
        "shiny": {"lower": [19, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [1, 40, 80], "upper": [31, 255, 255]},
        "confirm_threshold": 157,
    },
    "starmie": {  # #121 hue_diff=39
        "shiny": {"lower": [98, 40, 80], "upper": [109, 255, 255]},
        "normal": {"lower": [136, 40, 80], "upper": [155, 255, 255]},
        "confirm_threshold": 297,
    },
    "mr_mime": {  # #122 hue_diff=36
        "shiny": {"lower": [35, 40, 80], "upper": [51, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [10, 255, 255]},
        "confirm_threshold": 209,
    },
    "jynx": {  # #124 hue_diff=14
        "shiny": {"lower": [154, 40, 80], "upper": [171, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [7, 255, 255]},
        "confirm_threshold": 325,
    },
    "magmar": {  # #126 hue_diff=23
        "shiny": {"lower": [165, 40, 80], "upper": [179, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [33, 255, 255]},
        "confirm_threshold": 269,
    },
    "pinsir": {  # #127 hue_diff=85
        "shiny": {"lower": [110, 40, 80], "upper": [122, 255, 255]},
        "normal": {"lower": [8, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 296,
    },
    "tauros": {  # #128 hue_diff=9
        "shiny": {"lower": [16, 40, 80], "upper": [50, 255, 255]},
        "normal": {"lower": [11, 40, 80], "upper": [27, 255, 255]},
        "confirm_threshold": 376,
    },
    "magikarp": {  # #129 hue_diff=26
        "shiny": {"lower": [6, 40, 80], "upper": [39, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [17, 255, 255]},
        "confirm_threshold": 169,
    },
    "gyarados": {  # #130 hue_diff=74
        "shiny": {"lower": [0, 40, 80], "upper": [25, 255, 255]},
        "normal": {"lower": [102, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 442,
    },
    "lapras": {  # #131 hue_diff=78
        "shiny": {"lower": [122, 40, 80], "upper": [136, 255, 255]},
        "normal": {"lower": [5, 40, 80], "upper": [30, 255, 255]},
        "confirm_threshold": 319,
    },
    "ditto": {  # #132 hue_diff=60
        "shiny": {"lower": [94, 40, 80], "upper": [109, 255, 255]},
        "normal": {"lower": [154, 40, 80], "upper": [170, 255, 255]},
        "confirm_threshold": 165,
    },
    "eevee": {  # #133 hue_diff=89
        "shiny": {"lower": [103, 40, 80], "upper": [119, 255, 255]},
        "normal": {"lower": [11, 40, 80], "upper": [31, 255, 255]},
        "confirm_threshold": 50,
    },
    "vaporeon": {  # #134 hue_diff=63
        "shiny": {"lower": [138, 40, 80], "upper": [166, 255, 255]},
        "normal": {"lower": [77, 40, 80], "upper": [88, 255, 255]},
        "confirm_threshold": 219,
    },
    "jolteon": {  # #135 hue_diff=11
        "shiny": {"lower": [31, 40, 80], "upper": [46, 255, 255]},
        "normal": {"lower": [15, 40, 80], "upper": [33, 255, 255]},
        "confirm_threshold": 165,
    },
    "porygon": {  # #137 hue_diff=51
        "shiny": {"lower": [135, 40, 80], "upper": [155, 255, 255]},
        "normal": {"lower": [81, 40, 80], "upper": [104, 255, 255]},
        "confirm_threshold": 137,
    },
    "omastar": {  # #139 hue_diff=55
        "shiny": {"lower": [25, 40, 80], "upper": [38, 255, 255]},
        "normal": {"lower": [82, 40, 80], "upper": [92, 255, 255]},
        "confirm_threshold": 296,
    },
    "kabuto": {  # #140 hue_diff=20
        "shiny": {"lower": [19, 40, 80], "upper": [47, 255, 255]},
        "normal": {"lower": [10, 40, 80], "upper": [29, 255, 255]},
        "confirm_threshold": 113,
    },
    "kabutops": {  # #141 hue_diff=16
        "shiny": {"lower": [31, 40, 80], "upper": [44, 255, 255]},
        "normal": {"lower": [16, 40, 80], "upper": [28, 255, 255]},
        "confirm_threshold": 179,
    },
    "aerodactyl": {  # #142 hue_diff=52
        "shiny": {"lower": [142, 40, 80], "upper": [160, 255, 255]},
        "normal": {"lower": [93, 40, 80], "upper": [103, 255, 255]},
        "confirm_threshold": 311,
    },
    "moltres": {  # #146 hue_diff=24
        "shiny": {"lower": [0, 40, 80], "upper": [23, 255, 255]},
        "normal": {"lower": [7, 40, 80], "upper": [34, 255, 255]},
        "confirm_threshold": 435,
    },
    "dratini": {  # #147 hue_diff=75
        "shiny": {"lower": [25, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [128, 40, 80], "upper": [140, 255, 255]},
        "confirm_threshold": 192,
    },
    "dragonair": {  # #148 hue_diff=48
        "shiny": {"lower": [139, 40, 80], "upper": [161, 255, 255]},
        "normal": {"lower": [96, 40, 80], "upper": [116, 255, 255]},
        "confirm_threshold": 205,
    },
    "dragonite": {  # #149 hue_diff=20
        "shiny": {"lower": [20, 40, 80], "upper": [65, 255, 255]},
        "normal": {"lower": [16, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 499,
    },
    "mewtwo": {  # #150 hue_diff=87
        "shiny": {"lower": [25, 40, 80], "upper": [50, 255, 255]},
        "normal": {"lower": [115, 40, 80], "upper": [145, 255, 255]},
        "confirm_threshold": 154,
    },
    "mew": {  # #151 hue_diff=86
        "shiny": {"lower": [94, 40, 80], "upper": [114, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "confirm_threshold": 137,
    },
    "chikorita": {  # #152 hue_diff=9
        "shiny": {"lower": [11, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [32, 40, 80], "upper": [60, 255, 255]},
        "confirm_threshold": 158,
    },
    "bayleef": {  # #153 hue_diff=15
        "shiny": {"lower": [3, 40, 80], "upper": [29, 255, 255]},
        "normal": {"lower": [18, 40, 80], "upper": [53, 255, 255]},
        "confirm_threshold": 316,
    },
    "meganium": {  # #154 hue_diff=17
        "shiny": {"lower": [6, 40, 80], "upper": [33, 255, 255]},
        "normal": {"lower": [21, 40, 80], "upper": [61, 255, 255]},
        "confirm_threshold": 500,
    },
    "totodile": {  # #158 hue_diff=19
        "shiny": {"lower": [66, 40, 80], "upper": [88, 255, 255]},
        "normal": {"lower": [97, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 149,
    },
    "croconaw": {  # #159 hue_diff=14
        "shiny": {"lower": [76, 40, 80], "upper": [106, 255, 255]},
        "normal": {"lower": [97, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 255,
    },
    "feraligatr": {  # #160 hue_diff=14
        "shiny": {"lower": [81, 40, 80], "upper": [109, 255, 255]},
        "normal": {"lower": [97, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 500,
    },
    "furret": {  # #162 hue_diff=17
        "shiny": {"lower": [3, 40, 80], "upper": [176, 255, 255]},
        "normal": {"lower": [4, 40, 80], "upper": [30, 255, 255]},
        "confirm_threshold": 293,
    },
    "noctowl": {  # #164 hue_diff=9
        "shiny": {"lower": [14, 40, 80], "upper": [38, 255, 255]},
        "normal": {"lower": [5, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 274,
    },
    "ledyba": {  # #165 hue_diff=20
        "shiny": {"lower": [10, 40, 80], "upper": [33, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [31, 255, 255]},
        "confirm_threshold": 101,
    },
    "ledian": {  # #166 hue_diff=11
        "shiny": {"lower": [10, 40, 80], "upper": [33, 255, 255]},
        "normal": {"lower": [2, 40, 80], "upper": [31, 255, 255]},
        "confirm_threshold": 155,
    },
    "spinarak": {  # #167 hue_diff=55
        "shiny": {"lower": [91, 40, 80], "upper": [115, 255, 255]},
        "normal": {"lower": [21, 40, 80], "upper": [52, 255, 255]},
        "confirm_threshold": 107,
    },
    "ariados": {  # #168 hue_diff=82
        "shiny": {"lower": [97, 40, 80], "upper": [115, 255, 255]},
        "normal": {"lower": [2, 40, 80], "upper": [32, 255, 255]},
        "confirm_threshold": 227,
    },
    "crobat": {  # #169 hue_diff=25
        "shiny": {"lower": [164, 40, 80], "upper": [179, 255, 255]},
        "normal": {"lower": [137, 40, 80], "upper": [153, 255, 255]},
        "confirm_threshold": 262,
    },
    "lanturn": {  # #171 hue_diff=25
        "shiny": {"lower": [130, 40, 80], "upper": [148, 255, 255]},
        "normal": {"lower": [97, 40, 80], "upper": [116, 255, 255]},
        "confirm_threshold": 310,
    },
    "cleffa": {  # #173 hue_diff=15
        "shiny": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "normal": {"lower": [3, 40, 80], "upper": [25, 255, 255]},
        "confirm_threshold": 103,
    },
    "igglybuff": {  # #174 hue_diff=33
        "shiny": {"lower": [157, 40, 80], "upper": [178, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [20, 255, 255]},
        "confirm_threshold": 103,
    },
    "togetic": {  # #176 hue_diff=86
        "shiny": {"lower": [15, 40, 80], "upper": [33, 255, 255]},
        "normal": {"lower": [109, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 79,
    },
    "natu": {  # #177 hue_diff=17
        "shiny": {"lower": [17, 40, 80], "upper": [47, 255, 255]},
        "normal": {"lower": [39, 40, 80], "upper": [63, 255, 255]},
        "confirm_threshold": 67,
    },
    "xatu": {  # #178 hue_diff=16
        "shiny": {"lower": [20, 40, 80], "upper": [47, 255, 255]},
        "normal": {"lower": [39, 40, 80], "upper": [63, 255, 255]},
        "confirm_threshold": 113,
    },
    "mareep": {  # #179 hue_diff=21
        "shiny": {"lower": [0, 40, 80], "upper": [178, 255, 255]},
        "normal": {"lower": [12, 40, 80], "upper": [31, 255, 255]},
        "confirm_threshold": 180,
    },
    "flaaffy": {  # #180 hue_diff=51
        "shiny": {"lower": [160, 40, 80], "upper": [179, 255, 255]},
        "normal": {"lower": [99, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 136,
    },
    "ampharos": {  # #181 hue_diff=42
        "shiny": {"lower": [158, 40, 80], "upper": [172, 255, 255]},
        "normal": {"lower": [5, 40, 80], "upper": [32, 255, 255]},
        "confirm_threshold": 181,
    },
    "marill": {  # #183 hue_diff=50
        "shiny": {"lower": [55, 40, 80], "upper": [72, 255, 255]},
        "normal": {"lower": [103, 40, 80], "upper": [118, 255, 255]},
        "confirm_threshold": 134,
    },
    "azumarill": {  # #184 hue_diff=78
        "shiny": {"lower": [11, 40, 80], "upper": [32, 255, 255]},
        "normal": {"lower": [97, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 196,
    },
    "sudowoodo": {  # #185 hue_diff=13
        "shiny": {"lower": [25, 40, 80], "upper": [39, 255, 255]},
        "normal": {"lower": [15, 40, 80], "upper": [27, 255, 255]},
        "confirm_threshold": 205,
    },
    "politoed": {  # #186 hue_diff=61
        "shiny": {"lower": [93, 40, 80], "upper": [113, 255, 255]},
        "normal": {"lower": [17, 40, 80], "upper": [53, 255, 255]},
        "confirm_threshold": 215,
    },
    "hoppip": {  # #187 hue_diff=40
        "shiny": {"lower": [34, 40, 80], "upper": [59, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [14, 255, 255]},
        "confirm_threshold": 176,
    },
    "skiploom": {  # #188 hue_diff=74
        "shiny": {"lower": [154, 40, 80], "upper": [167, 255, 255]},
        "normal": {"lower": [41, 40, 80], "upper": [58, 255, 255]},
        "confirm_threshold": 173,
    },
    "jumpluff": {  # #189 hue_diff=50
        "shiny": {"lower": [145, 40, 80], "upper": [175, 255, 255]},
        "normal": {"lower": [18, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 262,
    },
    "aipom": {  # #190 hue_diff=29
        "shiny": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "normal": {"lower": [134, 40, 80], "upper": [145, 255, 255]},
        "confirm_threshold": 175,
    },
    "sunflora": {  # #192 hue_diff=14
        "shiny": {"lower": [19, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [21, 40, 80], "upper": [49, 255, 255]},
        "confirm_threshold": 233,
    },
    "yanma": {  # #193 hue_diff=87
        "shiny": {"lower": [90, 40, 80], "upper": [115, 255, 255]},
        "normal": {"lower": [4, 40, 80], "upper": [26, 255, 255]},
        "confirm_threshold": 194,
    },
    "wooper": {  # #194 hue_diff=71
        "shiny": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "normal": {"lower": [85, 40, 80], "upper": [116, 255, 255]},
        "confirm_threshold": 131,
    },
    "quagsire": {  # #195 hue_diff=45
        "shiny": {"lower": [138, 40, 80], "upper": [163, 255, 255]},
        "normal": {"lower": [95, 40, 80], "upper": [115, 255, 255]},
        "confirm_threshold": 379,
    },
    "espeon": {  # #196 hue_diff=84
        "shiny": {"lower": [39, 40, 80], "upper": [65, 255, 255]},
        "normal": {"lower": [128, 40, 80], "upper": [146, 255, 255]},
        "confirm_threshold": 245,
    },
    "murkrow": {  # #198 hue_diff=65
        "shiny": {"lower": [149, 40, 80], "upper": [167, 255, 255]},
        "normal": {"lower": [85, 40, 80], "upper": [95, 255, 255]},
        "confirm_threshold": 162,
    },
    "slowking": {  # #199 hue_diff=18
        "shiny": {"lower": [163, 40, 80], "upper": [178, 255, 255]},
        "normal": {"lower": [2, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 228,
    },
    "misdreavus": {  # #200 hue_diff=58
        "shiny": {"lower": [4, 40, 80], "upper": [31, 255, 255]},
        "normal": {"lower": [78, 40, 80], "upper": [101, 255, 255]},
        "confirm_threshold": 183,
    },
    "wobbuffet": {  # #202 hue_diff=55
        "shiny": {"lower": [149, 40, 80], "upper": [169, 255, 255]},
        "normal": {"lower": [91, 40, 80], "upper": [104, 255, 255]},
        "confirm_threshold": 350,
    },
    "girafarig": {  # #203 hue_diff=8
        "shiny": {"lower": [10, 40, 80], "upper": [27, 255, 255]},
        "normal": {"lower": [10, 40, 80], "upper": [30, 255, 255]},
        "confirm_threshold": 322,
    },
    "pineco": {  # #204 hue_diff=80
        "shiny": {"lower": [0, 40, 80], "upper": [29, 255, 255]},
        "normal": {"lower": [85, 40, 80], "upper": [113, 255, 255]},
        "confirm_threshold": 244,
    },
    "forretress": {  # #205 hue_diff=49
        "shiny": {"lower": [8, 40, 80], "upper": [33, 255, 255]},
        "normal": {"lower": [145, 40, 80], "upper": [176, 255, 255]},
        "confirm_threshold": 368,
    },
    "gligar": {  # #207 hue_diff=27
        "shiny": {"lower": [105, 40, 80], "upper": [121, 255, 255]},
        "normal": {"lower": [125, 40, 80], "upper": [148, 255, 255]},
        "confirm_threshold": 305,
    },
    "steelix": {  # #208 hue_diff=82
        "shiny": {"lower": [8, 40, 80], "upper": [29, 255, 255]},
        "normal": {"lower": [97, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 493,
    },
    "granbull": {  # #210 hue_diff=47
        "shiny": {"lower": [8, 40, 80], "upper": [22, 255, 255]},
        "normal": {"lower": [138, 40, 80], "upper": [163, 255, 255]},
        "confirm_threshold": 300,
    },
    "qwilfish": {  # #211 hue_diff=40
        "shiny": {"lower": [150, 40, 80], "upper": [164, 255, 255]},
        "normal": {"lower": [101, 40, 80], "upper": [120, 255, 255]},
        "confirm_threshold": 194,
    },
    "scizor": {  # #212 hue_diff=22
        "shiny": {"lower": [27, 40, 80], "upper": [40, 255, 255]},
        "normal": {"lower": [3, 40, 80], "upper": [23, 255, 255]},
        "confirm_threshold": 365,
    },
    "shuckle": {  # #213 hue_diff=22
        "shiny": {"lower": [15, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [2, 40, 80], "upper": [28, 255, 255]},
        "confirm_threshold": 149,
    },
    "heracross": {  # #214 hue_diff=38
        "shiny": {"lower": [145, 40, 80], "upper": [164, 255, 255]},
        "normal": {"lower": [108, 40, 80], "upper": [122, 255, 255]},
        "confirm_threshold": 292,
    },
    "sneasel": {  # #215 hue_diff=87
        "shiny": {"lower": [163, 40, 80], "upper": [175, 255, 255]},
        "normal": {"lower": [55, 40, 80], "upper": [83, 255, 255]},
        "confirm_threshold": 175,
    },
    "teddiursa": {  # #216 hue_diff=29
        "shiny": {"lower": [22, 40, 80], "upper": [54, 255, 255]},
        "normal": {"lower": [11, 40, 80], "upper": [32, 255, 255]},
        "confirm_threshold": 168,
    },
    "ursaring": {  # #217 hue_diff=23
        "shiny": {"lower": [34, 40, 80], "upper": [51, 255, 255]},
        "normal": {"lower": [15, 40, 80], "upper": [28, 255, 255]},
        "confirm_threshold": 445,
    },
    "slugma": {  # #218 hue_diff=12
        "shiny": {"lower": [15, 40, 80], "upper": [30, 255, 255]},
        "normal": {"lower": [2, 40, 80], "upper": [26, 255, 255]},
        "confirm_threshold": 50,
    },
    "magcargo": {  # #219 hue_diff=39
        "shiny": {"lower": [132, 40, 80], "upper": [162, 255, 255]},
        "normal": {"lower": [2, 40, 80], "upper": [26, 255, 255]},
        "confirm_threshold": 254,
    },
    "swinub": {  # #220 hue_diff=79
        "shiny": {"lower": [95, 40, 80], "upper": [125, 255, 255]},
        "normal": {"lower": [16, 40, 80], "upper": [28, 255, 255]},
        "confirm_threshold": 50,
    },
    "corsola": {  # #222 hue_diff=70
        "shiny": {"lower": [90, 40, 80], "upper": [113, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "confirm_threshold": 214,
    },
    "remoraid": {  # #223 hue_diff=61
        "shiny": {"lower": [140, 40, 80], "upper": [155, 255, 255]},
        "normal": {"lower": [79, 40, 80], "upper": [106, 255, 255]},
        "confirm_threshold": 138,
    },
    "octillery": {  # #224 hue_diff=15
        "shiny": {"lower": [10, 40, 80], "upper": [40, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [25, 255, 255]},
        "confirm_threshold": 249,
    },
    "delibird": {  # #225 hue_diff=27
        "shiny": {"lower": [150, 40, 80], "upper": [167, 255, 255]},
        "normal": {"lower": [4, 40, 80], "upper": [27, 255, 255]},
        "confirm_threshold": 199,
    },
    "skarmory": {  # #227 hue_diff=18
        "shiny": {"lower": [15, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [13, 255, 255]},
        "confirm_threshold": 369,
    },
    "houndour": {  # #228 hue_diff=75
        "shiny": {"lower": [98, 40, 80], "upper": [112, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [24, 255, 255]},
        "confirm_threshold": 142,
    },
    "houndoom": {  # #229 hue_diff=65
        "shiny": {"lower": [105, 40, 80], "upper": [120, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [24, 255, 255]},
        "confirm_threshold": 237,
    },
    "kingdra": {  # #230 hue_diff=42
        "shiny": {"lower": [134, 40, 80], "upper": [155, 255, 255]},
        "normal": {"lower": [94, 40, 80], "upper": [114, 255, 255]},
        "confirm_threshold": 346,
    },
    "donphan": {  # #232 hue_diff=60
        "shiny": {"lower": [8, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [85, 40, 80], "upper": [95, 255, 255]},
        "confirm_threshold": 382,
    },
    "porygon2": {  # #233 hue_diff=74
        "shiny": {"lower": [102, 40, 80], "upper": [115, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [20, 255, 255]},
        "confirm_threshold": 132,
    },
    "stantler": {  # #234 hue_diff=19
        "shiny": {"lower": [14, 40, 80], "upper": [43, 255, 255]},
        "normal": {"lower": [11, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 337,
    },
    "smeargle": {  # #235 hue_diff=9
        "shiny": {"lower": [0, 40, 80], "upper": [29, 255, 255]},
        "normal": {"lower": [16, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 265,
    },
    "tyrogue": {  # #236 hue_diff=56
        "shiny": {"lower": [10, 40, 80], "upper": [28, 255, 255]},
        "normal": {"lower": [139, 40, 80], "upper": [162, 255, 255]},
        "confirm_threshold": 138,
    },
    "magby": {  # #240 hue_diff=9
        "shiny": {"lower": [4, 40, 80], "upper": [33, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [29, 255, 255]},
        "confirm_threshold": 123,
    },
    "miltank": {  # #241 hue_diff=78
        "shiny": {"lower": [100, 40, 80], "upper": [119, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [28, 255, 255]},
        "confirm_threshold": 226,
    },
    "entei": {  # #244 hue_diff=14
        "shiny": {"lower": [0, 40, 80], "upper": [26, 255, 255]},
        "normal": {"lower": [15, 40, 80], "upper": [28, 255, 255]},
        "confirm_threshold": 323,
    },
    "larvitar": {  # #246 hue_diff=27
        "shiny": {"lower": [28, 40, 80], "upper": [41, 255, 255]},
        "normal": {"lower": [55, 40, 80], "upper": [65, 255, 255]},
        "confirm_threshold": 162,
    },
    "pupitar": {  # #247 hue_diff=33
        "shiny": {"lower": [133, 40, 80], "upper": [151, 255, 255]},
        "normal": {"lower": [96, 40, 80], "upper": [110, 255, 255]},
        "confirm_threshold": 227,
    },
    "tyranitar": {  # #248 hue_diff=40
        "shiny": {"lower": [10, 40, 80], "upper": [25, 255, 255]},
        "normal": {"lower": [55, 40, 80], "upper": [65, 255, 255]},
        "confirm_threshold": 500,
    },
    "lugia": {  # #249 hue_diff=12
        "shiny": {"lower": [102, 40, 80], "upper": [118, 255, 255]},
        "normal": {"lower": [99, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 317,
    },
    "ho_oh": {  # #250 hue_diff=8
        "shiny": {"lower": [0, 40, 80], "upper": [31, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [32, 255, 255]},
        "confirm_threshold": 396,
    },
    "celebi": {  # #251 hue_diff=62
        "shiny": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "normal": {"lower": [37, 40, 80], "upper": [65, 255, 255]},
        "confirm_threshold": 85,
    },
    "treecko": {  # #252 hue_diff=52
        "shiny": {"lower": [80, 40, 80], "upper": [99, 255, 255]},
        "normal": {"lower": [34, 40, 80], "upper": [49, 255, 255]},
        "confirm_threshold": 197,
    },
    "grovyle": {  # #253 hue_diff=78
        "shiny": {"lower": [0, 40, 80], "upper": [26, 255, 255]},
        "normal": {"lower": [81, 40, 80], "upper": [102, 255, 255]},
        "confirm_threshold": 353,
    },
    "sceptile": {  # #254 hue_diff=50
        "shiny": {"lower": [80, 40, 80], "upper": [99, 255, 255]},
        "normal": {"lower": [36, 40, 80], "upper": [54, 255, 255]},
        "confirm_threshold": 431,
    },
    "torchic": {  # #255 hue_diff=15
        "shiny": {"lower": [1, 40, 80], "upper": [29, 255, 255]},
        "normal": {"lower": [1, 40, 80], "upper": [27, 255, 255]},
        "confirm_threshold": 178,
    },
    "blaziken": {  # #257 hue_diff=14
        "shiny": {"lower": [0, 40, 80], "upper": [178, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [27, 255, 255]},
        "confirm_threshold": 298,
    },
    "mudkip": {  # #258 hue_diff=40
        "shiny": {"lower": [138, 40, 80], "upper": [149, 255, 255]},
        "normal": {"lower": [97, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 201,
    },
    "marshtomp": {  # #259 hue_diff=23
        "shiny": {"lower": [138, 40, 80], "upper": [148, 255, 255]},
        "normal": {"lower": [115, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 237,
    },
    "swampert": {  # #260 hue_diff=40
        "shiny": {"lower": [121, 40, 80], "upper": [155, 255, 255]},
        "normal": {"lower": [97, 40, 80], "upper": [121, 255, 255]},
        "confirm_threshold": 446,
    },
    "poochyena": {  # #261 hue_diff=90
        "shiny": {"lower": [8, 40, 80], "upper": [26, 255, 255]},
        "normal": {"lower": [105, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 187,
    },
    "mightyena": {  # #262 hue_diff=73
        "shiny": {"lower": [8, 40, 80], "upper": [28, 255, 255]},
        "normal": {"lower": [108, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 339,
    },
    "linoone": {  # #264 hue_diff=11
        "shiny": {"lower": [3, 40, 80], "upper": [29, 255, 255]},
        "normal": {"lower": [8, 40, 80], "upper": [29, 255, 255]},
        "confirm_threshold": 234,
    },
    "wurmple": {  # #265 hue_diff=19
        "shiny": {"lower": [154, 40, 80], "upper": [168, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "confirm_threshold": 152,
    },
    "beautifly": {  # #267 hue_diff=52
        "shiny": {"lower": [153, 40, 80], "upper": [166, 255, 255]},
        "normal": {"lower": [10, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 290,
    },
    "cascoon": {  # #268 hue_diff=87
        "shiny": {"lower": [37, 40, 80], "upper": [53, 255, 255]},
        "normal": {"lower": [130, 40, 80], "upper": [150, 255, 255]},
        "confirm_threshold": 174,
    },
    "dustox": {  # #269 hue_diff=12
        "shiny": {"lower": [0, 40, 80], "upper": [33, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [168, 255, 255]},
        "confirm_threshold": 316,
    },
    "lotad": {  # #270 hue_diff=43
        "shiny": {"lower": [88, 40, 80], "upper": [102, 255, 255]},
        "normal": {"lower": [43, 40, 80], "upper": [55, 255, 255]},
        "confirm_threshold": 177,
    },
    "lombre": {  # #271 hue_diff=57
        "shiny": {"lower": [88, 40, 80], "upper": [99, 255, 255]},
        "normal": {"lower": [31, 40, 80], "upper": [60, 255, 255]},
        "confirm_threshold": 265,
    },
    "ludicolo": {  # #272 hue_diff=56
        "shiny": {"lower": [81, 40, 80], "upper": [99, 255, 255]},
        "normal": {"lower": [8, 40, 80], "upper": [55, 255, 255]},
        "confirm_threshold": 500,
    },
    "nuzleaf": {  # #274 hue_diff=30
        "shiny": {"lower": [0, 40, 80], "upper": [170, 255, 255]},
        "normal": {"lower": [145, 40, 80], "upper": [170, 255, 255]},
        "confirm_threshold": 214,
    },
    "shiftry": {  # #275 hue_diff=77
        "shiny": {"lower": [3, 40, 80], "upper": [50, 255, 255]},
        "normal": {"lower": [123, 40, 80], "upper": [133, 255, 255]},
        "confirm_threshold": 456,
    },
    "taillow": {  # #276 hue_diff=38
        "shiny": {"lower": [70, 40, 80], "upper": [86, 255, 255]},
        "normal": {"lower": [108, 40, 80], "upper": [120, 255, 255]},
        "confirm_threshold": 125,
    },
    "swellow": {  # #277 hue_diff=36
        "shiny": {"lower": [70, 40, 80], "upper": [86, 255, 255]},
        "normal": {"lower": [106, 40, 80], "upper": [120, 255, 255]},
        "confirm_threshold": 278,
    },
    "wingull": {  # #278 hue_diff=11
        "shiny": {"lower": [130, 40, 80], "upper": [142, 255, 255]},
        "normal": {"lower": [104, 40, 80], "upper": [131, 255, 255]},
        "confirm_threshold": 68,
    },
    "ralts": {  # #280 hue_diff=41
        "shiny": {"lower": [88, 40, 80], "upper": [106, 255, 255]},
        "normal": {"lower": [43, 40, 80], "upper": [75, 255, 255]},
        "confirm_threshold": 90,
    },
    "kirlia": {  # #281 hue_diff=41
        "shiny": {"lower": [88, 40, 80], "upper": [111, 255, 255]},
        "normal": {"lower": [43, 40, 80], "upper": [75, 255, 255]},
        "confirm_threshold": 173,
    },
    "gardevoir": {  # #282 hue_diff=83
        "shiny": {"lower": [127, 40, 80], "upper": [148, 255, 255]},
        "normal": {"lower": [43, 40, 80], "upper": [75, 255, 255]},
        "confirm_threshold": 254,
    },
    "surskit": {  # #283 hue_diff=20
        "shiny": {"lower": [105, 40, 80], "upper": [115, 255, 255]},
        "normal": {"lower": [85, 40, 80], "upper": [109, 255, 255]},
        "confirm_threshold": 94,
    },
    "masquerain": {  # #284 hue_diff=13
        "shiny": {"lower": [5, 40, 80], "upper": [53, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [22, 255, 255]},
        "confirm_threshold": 302,
    },
    "breloom": {  # #286 hue_diff=14
        "shiny": {"lower": [0, 40, 80], "upper": [28, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [27, 255, 255]},
        "confirm_threshold": 286,
    },
    "slakoth": {  # #287 hue_diff=31
        "shiny": {"lower": [0, 40, 80], "upper": [173, 255, 255]},
        "normal": {"lower": [7, 40, 80], "upper": [24, 255, 255]},
        "confirm_threshold": 211,
    },
    "vigoroth": {  # #288 hue_diff=23
        "shiny": {"lower": [8, 40, 80], "upper": [30, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [175, 255, 255]},
        "confirm_threshold": 259,
    },
    "slaking": {  # #289 hue_diff=8
        "shiny": {"lower": [2, 40, 80], "upper": [28, 255, 255]},
        "normal": {"lower": [7, 40, 80], "upper": [179, 255, 255]},
        "confirm_threshold": 500,
    },
    "ninjask": {  # #291 hue_diff=82
        "shiny": {"lower": [0, 40, 80], "upper": [29, 255, 255]},
        "normal": {"lower": [115, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 175,
    },
    "shedinja": {  # #292 hue_diff=13
        "shiny": {"lower": [9, 40, 80], "upper": [24, 255, 255]},
        "normal": {"lower": [16, 40, 80], "upper": [32, 255, 255]},
        "confirm_threshold": 203,
    },
    "whismur": {  # #293 hue_diff=13
        "shiny": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "normal": {"lower": [150, 40, 80], "upper": [170, 255, 255]},
        "confirm_threshold": 221,
    },
    "loudred": {  # #294 hue_diff=34
        "shiny": {"lower": [153, 40, 80], "upper": [173, 255, 255]},
        "normal": {"lower": [115, 40, 80], "upper": [129, 255, 255]},
        "confirm_threshold": 432,
    },
    "exploud": {  # #295 hue_diff=49
        "shiny": {"lower": [0, 40, 80], "upper": [178, 255, 255]},
        "normal": {"lower": [115, 40, 80], "upper": [129, 255, 255]},
        "confirm_threshold": 500,
    },
    "hariyama": {  # #297 hue_diff=16
        "shiny": {"lower": [0, 40, 80], "upper": [178, 255, 255]},
        "normal": {"lower": [4, 40, 80], "upper": [28, 255, 255]},
        "confirm_threshold": 500,
    },
    "azurill": {  # #298 hue_diff=42
        "shiny": {"lower": [55, 40, 80], "upper": [85, 255, 255]},
        "normal": {"lower": [103, 40, 80], "upper": [118, 255, 255]},
        "confirm_threshold": 185,
    },
    "nosepass": {  # #299 hue_diff=84
        "shiny": {"lower": [1, 40, 80], "upper": [28, 255, 255]},
        "normal": {"lower": [93, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 236,
    },
    "delcatty": {  # #301 hue_diff=14
        "shiny": {"lower": [0, 40, 80], "upper": [29, 255, 255]},
        "normal": {"lower": [8, 40, 80], "upper": [179, 255, 255]},
        "confirm_threshold": 244,
    },
    "sableye": {  # #302 hue_diff=40
        "shiny": {"lower": [5, 40, 80], "upper": [19, 255, 255]},
        "normal": {"lower": [139, 40, 80], "upper": [158, 255, 255]},
        "confirm_threshold": 183,
    },
    "mawile": {  # #303 hue_diff=35
        "shiny": {"lower": [158, 40, 80], "upper": [170, 255, 255]},
        "normal": {"lower": [13, 40, 80], "upper": [26, 255, 255]},
        "confirm_threshold": 299,
    },
    "aron": {  # #304 hue_diff=73
        "shiny": {"lower": [25, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [98, 40, 80], "upper": [116, 255, 255]},
        "confirm_threshold": 50,
    },
    "lairon": {  # #305 hue_diff=34
        "shiny": {"lower": [81, 40, 80], "upper": [99, 255, 255]},
        "normal": {"lower": [115, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 219,
    },
    "aggron": {  # #306 hue_diff=86
        "shiny": {"lower": [81, 40, 80], "upper": [99, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "confirm_threshold": 405,
    },
    "meditite": {  # #307 hue_diff=69
        "shiny": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "normal": {"lower": [101, 40, 80], "upper": [113, 255, 255]},
        "confirm_threshold": 73,
    },
    "medicham": {  # #308 hue_diff=74
        "shiny": {"lower": [101, 40, 80], "upper": [113, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [26, 255, 255]},
        "confirm_threshold": 231,
    },
    "electrike": {  # #309 hue_diff=51
        "shiny": {"lower": [98, 40, 80], "upper": [125, 255, 255]},
        "normal": {"lower": [47, 40, 80], "upper": [72, 255, 255]},
        "confirm_threshold": 185,
    },
    "manectric": {  # #310 hue_diff=9
        "shiny": {"lower": [13, 40, 80], "upper": [28, 255, 255]},
        "normal": {"lower": [18, 40, 80], "upper": [40, 255, 255]},
        "confirm_threshold": 224,
    },
    "plusle": {  # #311 hue_diff=15
        "shiny": {"lower": [0, 40, 80], "upper": [30, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [29, 255, 255]},
        "confirm_threshold": 150,
    },
    "minun": {  # #312 hue_diff=65
        "shiny": {"lower": [81, 40, 80], "upper": [99, 255, 255]},
        "normal": {"lower": [16, 40, 80], "upper": [29, 255, 255]},
        "confirm_threshold": 139,
    },
    "volbeat": {  # #313 hue_diff=39
        "shiny": {"lower": [135, 40, 80], "upper": [149, 255, 255]},
        "normal": {"lower": [100, 40, 80], "upper": [118, 255, 255]},
        "confirm_threshold": 194,
    },
    "illumise": {  # #314 hue_diff=41
        "shiny": {"lower": [97, 40, 80], "upper": [109, 255, 255]},
        "normal": {"lower": [138, 40, 80], "upper": [155, 255, 255]},
        "confirm_threshold": 198,
    },
    "gulpin": {  # #316 hue_diff=53
        "shiny": {"lower": [98, 40, 80], "upper": [114, 255, 255]},
        "normal": {"lower": [45, 40, 80], "upper": [58, 255, 255]},
        "confirm_threshold": 153,
    },
    "swalot": {  # #317 hue_diff=28
        "shiny": {"lower": [100, 40, 80], "upper": [120, 255, 255]},
        "normal": {"lower": [128, 40, 80], "upper": [140, 255, 255]},
        "confirm_threshold": 327,
    },
    "carvanha": {  # #318 hue_diff=85
        "shiny": {"lower": [80, 40, 80], "upper": [90, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [25, 255, 255]},
        "confirm_threshold": 229,
    },
    "sharpedo": {  # #319 hue_diff=60
        "shiny": {"lower": [148, 40, 80], "upper": [175, 255, 255]},
        "normal": {"lower": [85, 40, 80], "upper": [110, 255, 255]},
        "confirm_threshold": 283,
    },
    "wailmer": {  # #320 hue_diff=31
        "shiny": {"lower": [130, 40, 80], "upper": [140, 255, 255]},
        "normal": {"lower": [99, 40, 80], "upper": [113, 255, 255]},
        "confirm_threshold": 282,
    },
    "wailord": {  # #321 hue_diff=22
        "shiny": {"lower": [130, 40, 80], "upper": [155, 255, 255]},
        "normal": {"lower": [100, 40, 80], "upper": [119, 255, 255]},
        "confirm_threshold": 179,
    },
    "numel": {  # #322 hue_diff=12
        "shiny": {"lower": [8, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [20, 40, 80], "upper": [46, 255, 255]},
        "confirm_threshold": 252,
    },
    "camerupt": {  # #323 hue_diff=75
        "shiny": {"lower": [115, 40, 80], "upper": [140, 255, 255]},
        "normal": {"lower": [7, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 434,
    },
    "spoink": {  # #325 hue_diff=87
        "shiny": {"lower": [3, 40, 80], "upper": [20, 255, 255]},
        "normal": {"lower": [100, 40, 80], "upper": [110, 255, 255]},
        "confirm_threshold": 113,
    },
    "grumpig": {  # #326 hue_diff=58
        "shiny": {"lower": [19, 40, 80], "upper": [33, 255, 255]},
        "normal": {"lower": [136, 40, 80], "upper": [172, 255, 255]},
        "confirm_threshold": 164,
    },
    "trapinch": {  # #328 hue_diff=69
        "shiny": {"lower": [75, 40, 80], "upper": [89, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [20, 255, 255]},
        "confirm_threshold": 152,
    },
    "vibrava": {  # #329 hue_diff=66
        "shiny": {"lower": [4, 40, 80], "upper": [31, 255, 255]},
        "normal": {"lower": [68, 40, 80], "upper": [81, 255, 255]},
        "confirm_threshold": 134,
    },
    "flygon": {  # #330 hue_diff=79
        "shiny": {"lower": [96, 40, 80], "upper": [106, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [5, 255, 255]},
        "confirm_threshold": 412,
    },
    "cacnea": {  # #331 hue_diff=18
        "shiny": {"lower": [4, 40, 80], "upper": [28, 255, 255]},
        "normal": {"lower": [18, 40, 80], "upper": [60, 255, 255]},
        "confirm_threshold": 186,
    },
    "cacturne": {  # #332 hue_diff=21
        "shiny": {"lower": [0, 40, 80], "upper": [28, 255, 255]},
        "normal": {"lower": [33, 40, 80], "upper": [53, 255, 255]},
        "confirm_threshold": 363,
    },
    "swablu": {  # #333 hue_diff=81
        "shiny": {"lower": [16, 40, 80], "upper": [31, 255, 255]},
        "normal": {"lower": [95, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 93,
    },
    "altaria": {  # #334 hue_diff=83
        "shiny": {"lower": [13, 40, 80], "upper": [26, 255, 255]},
        "normal": {"lower": [99, 40, 80], "upper": [115, 255, 255]},
        "confirm_threshold": 151,
    },
    "zangoose": {  # #335 hue_diff=75
        "shiny": {"lower": [97, 40, 80], "upper": [125, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "confirm_threshold": 90,
    },
    "barboach": {  # #339 hue_diff=87
        "shiny": {"lower": [14, 40, 80], "upper": [33, 255, 255]},
        "normal": {"lower": [97, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 91,
    },
    "corphish": {  # #341 hue_diff=12
        "shiny": {"lower": [0, 40, 80], "upper": [23, 255, 255]},
        "normal": {"lower": [5, 40, 80], "upper": [30, 255, 255]},
        "confirm_threshold": 190,
    },
    "lileep": {  # #345 hue_diff=60
        "shiny": {"lower": [74, 40, 80], "upper": [84, 255, 255]},
        "normal": {"lower": [6, 40, 80], "upper": [28, 255, 255]},
        "confirm_threshold": 280,
    },
    "cradily": {  # #346 hue_diff=67
        "shiny": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "normal": {"lower": [48, 40, 80], "upper": [80, 255, 255]},
        "confirm_threshold": 362,
    },
    "anorith": {  # #347 hue_diff=60
        "shiny": {"lower": [115, 40, 80], "upper": [125, 255, 255]},
        "normal": {"lower": [55, 40, 80], "upper": [65, 255, 255]},
        "confirm_threshold": 211,
    },
    "armaldo": {  # #348 hue_diff=64
        "shiny": {"lower": [0, 40, 80], "upper": [25, 255, 255]},
        "normal": {"lower": [105, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 406,
    },
    "feebas": {  # #349 hue_diff=37
        "shiny": {"lower": [168, 40, 80], "upper": [178, 255, 255]},
        "normal": {"lower": [10, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 171,
    },
    "milotic": {  # #350 hue_diff=11
        "shiny": {"lower": [111, 40, 80], "upper": [135, 255, 255]},
        "normal": {"lower": [100, 40, 80], "upper": [110, 255, 255]},
        "confirm_threshold": 478,
    },
    "banette": {  # #354 hue_diff=21
        "shiny": {"lower": [94, 40, 80], "upper": [115, 255, 255]},
        "normal": {"lower": [115, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 172,
    },
    "duskull": {  # #355 hue_diff=25
        "shiny": {"lower": [0, 40, 80], "upper": [30, 255, 255]},
        "normal": {"lower": [20, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 233,
    },
    "dusclops": {  # #356 hue_diff=10
        "shiny": {"lower": [0, 40, 80], "upper": [20, 255, 255]},
        "normal": {"lower": [3, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 318,
    },
    "tropius": {  # #357 hue_diff=25
        "shiny": {"lower": [16, 40, 80], "upper": [49, 255, 255]},
        "normal": {"lower": [44, 40, 80], "upper": [70, 255, 255]},
        "confirm_threshold": 500,
    },
    "chimecho": {  # #358 hue_diff=43
        "shiny": {"lower": [43, 40, 80], "upper": [75, 255, 255]},
        "normal": {"lower": [98, 40, 80], "upper": [119, 255, 255]},
        "confirm_threshold": 125,
    },
    "absol": {  # #359 hue_diff=85
        "shiny": {"lower": [0, 40, 80], "upper": [10, 255, 255]},
        "normal": {"lower": [85, 40, 80], "upper": [95, 255, 255]},
        "confirm_threshold": 217,
    },
    "wynaut": {  # #360 hue_diff=60
        "shiny": {"lower": [147, 40, 80], "upper": [179, 255, 255]},
        "normal": {"lower": [91, 40, 80], "upper": [107, 255, 255]},
        "confirm_threshold": 189,
    },
    "snorunt": {  # #361 hue_diff=83
        "shiny": {"lower": [88, 40, 80], "upper": [106, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [30, 255, 255]},
        "confirm_threshold": 152,
    },
    "glalie": {  # #362 hue_diff=20
        "shiny": {"lower": [93, 40, 80], "upper": [105, 255, 255]},
        "normal": {"lower": [104, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 99,
    },
    "sealeo": {  # #364 hue_diff=33
        "shiny": {"lower": [129, 40, 80], "upper": [151, 255, 255]},
        "normal": {"lower": [98, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 322,
    },
    "walrein": {  # #365 hue_diff=37
        "shiny": {"lower": [120, 40, 80], "upper": [151, 255, 255]},
        "normal": {"lower": [100, 40, 80], "upper": [118, 255, 255]},
        "confirm_threshold": 495,
    },
    "huntail": {  # #367 hue_diff=29
        "shiny": {"lower": [55, 40, 80], "upper": [75, 255, 255]},
        "normal": {"lower": [92, 40, 80], "upper": [105, 255, 255]},
        "confirm_threshold": 280,
    },
    "gorebyss": {  # #368 hue_diff=32
        "shiny": {"lower": [14, 40, 80], "upper": [32, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [178, 255, 255]},
        "confirm_threshold": 229,
    },
    "relicanth": {  # #369 hue_diff=89
        "shiny": {"lower": [92, 40, 80], "upper": [102, 255, 255]},
        "normal": {"lower": [3, 40, 80], "upper": [24, 255, 255]},
        "confirm_threshold": 327,
    },
    "luvdisc": {  # #370 hue_diff=17
        "shiny": {"lower": [5, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [25, 255, 255]},
        "confirm_threshold": 97,
    },
    "bagon": {  # #371 hue_diff=60
        "shiny": {"lower": [55, 40, 80], "upper": [71, 255, 255]},
        "normal": {"lower": [115, 40, 80], "upper": [135, 255, 255]},
        "confirm_threshold": 150,
    },
    "shelgon": {  # #372 hue_diff=15
        "shiny": {"lower": [40, 40, 80], "upper": [60, 255, 255]},
        "normal": {"lower": [10, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 310,
    },
    "salamence": {  # #373 hue_diff=60
        "shiny": {"lower": [55, 40, 80], "upper": [71, 255, 255]},
        "normal": {"lower": [108, 40, 80], "upper": [125, 255, 255]},
        "confirm_threshold": 472,
    },
    "beldum": {  # #374 hue_diff=86
        "shiny": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "normal": {"lower": [97, 40, 80], "upper": [121, 255, 255]},
        "confirm_threshold": 50,
    },
    "metang": {  # #375 hue_diff=87
        "shiny": {"lower": [11, 40, 80], "upper": [24, 255, 255]},
        "normal": {"lower": [97, 40, 80], "upper": [121, 255, 255]},
        "confirm_threshold": 74,
    },
    "metagross": {  # #376 hue_diff=89
        "shiny": {"lower": [11, 40, 80], "upper": [24, 255, 255]},
        "normal": {"lower": [97, 40, 80], "upper": [121, 255, 255]},
        "confirm_threshold": 56,
    },
    "regirock": {  # #377 hue_diff=11
        "shiny": {"lower": [3, 40, 80], "upper": [22, 255, 255]},
        "normal": {"lower": [7, 40, 80], "upper": [31, 255, 255]},
        "confirm_threshold": 497,
    },
    "regice": {  # #378 hue_diff=19
        "shiny": {"lower": [91, 40, 80], "upper": [110, 255, 255]},
        "normal": {"lower": [100, 40, 80], "upper": [133, 255, 255]},
        "confirm_threshold": 459,
    },
    "registeel": {  # #379 hue_diff=45
        "shiny": {"lower": [70, 40, 80], "upper": [88, 255, 255]},
        "normal": {"lower": [18, 40, 80], "upper": [35, 255, 255]},
        "confirm_threshold": 327,
    },
    "latias": {  # #380 hue_diff=9
        "shiny": {"lower": [4, 40, 80], "upper": [28, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "confirm_threshold": 241,
    },
    "latios": {  # #381 hue_diff=27
        "shiny": {"lower": [75, 40, 80], "upper": [95, 255, 255]},
        "normal": {"lower": [100, 40, 80], "upper": [121, 255, 255]},
        "confirm_threshold": 255,
    },
    "kyogre": {  # #382 hue_diff=42
        "shiny": {"lower": [145, 40, 80], "upper": [157, 255, 255]},
        "normal": {"lower": [102, 40, 80], "upper": [121, 255, 255]},
        "confirm_threshold": 341,
    },
    "groudon": {  # #383 hue_diff=37
        "shiny": {"lower": [25, 40, 80], "upper": [35, 255, 255]},
        "normal": {"lower": [0, 40, 80], "upper": [179, 255, 255]},
        "confirm_threshold": 376,
    },
    "rayquaza": {  # #384 hue_diff=53
        "shiny": {"lower": [10, 40, 80], "upper": [33, 255, 255]},
        "normal": {"lower": [68, 40, 80], "upper": [86, 255, 255]},
        "confirm_threshold": 50,
    },
    "deoxys": {  # #386 hue_diff=15
        "shiny": {"lower": [6, 40, 80], "upper": [33, 255, 255]},
        "normal": {"lower": [4, 40, 80], "upper": [16, 255, 255]},
        "confirm_threshold": 275,
    },
}
