"""
Auto-generated FRLG palette database for all 386 Pokémon.
Generated by tools/build_sprite_db.py from PokeAPI FRLG sprites.

Each entry maps a species name to its normal/shiny hue ranges,
enabling Tier-2 palette-based shiny detection.
"""

from dataclasses import dataclass, field
from typing import Dict, Optional, Tuple


@dataclass
class PaletteEntry:
    """HSV hue signature for a single Pokémon species."""
    normal_hues: Tuple[int, int]   # (low, high) dominant hue range for normal form
    shiny_hues: Tuple[int, int]    # (low, high) dominant hue range for shiny form
    min_sat: int = 30              # minimum saturation to count as 'colored'
    min_val: int = 30              # minimum value to count as 'colored'
    subtle: bool = False           # True if hue shift is < 10 (needs sparkle confirmation)
    description: str = ""


# Complete database: 386 Pokémon
FRLG_PALETTE_DB: Dict[str, PaletteEntry] = {
    "bulbasaur": PaletteEntry(
        normal_hues=(72, 99),
        shiny_hues=(32, 65),
        description="H:94->41 (diff=53)",
    ),  # #001
    "ivysaur": PaletteEntry(
        normal_hues=(79, 99),
        shiny_hues=(19, 51),
        description="H:94->39 (diff=55)",
    ),  # #002
    "venusaur": PaletteEntry(
        normal_hues=(50, 80),
        shiny_hues=(10, 60),
        description="H:75->35 (diff=40)",
    ),  # #003
    "charmander": PaletteEntry(
        normal_hues=(0, 24),
        shiny_hues=(6, 34),
        description="H:0->22 (diff=22)",
    ),  # #004
    "charmeleon": PaletteEntry(
        normal_hues=(0, 23),
        shiny_hues=(0, 32),
        description="H:0->20 (diff=20)",
    ),  # #005
    "charizard": PaletteEntry(
        normal_hues=(1, 27),
        shiny_hues=(78, 95),
        description="H:6->90 (diff=84)",
    ),  # #006
    "squirtle": PaletteEntry(
        normal_hues=(92, 113),
        shiny_hues=(89, 108),
        description="H:108->94 (diff=14)",
    ),  # #007
    "wartortle": PaletteEntry(
        normal_hues=(120, 135),
        shiny_hues=(127, 143),
        description="H:125->138 (diff=13)",
    ),  # #008
    "blastoise": PaletteEntry(
        normal_hues=(92, 116),
        shiny_hues=(115, 138),
        description="H:97->125 (diff=28)",
    ),  # #009
    "caterpie": PaletteEntry(
        normal_hues=(23, 52),
        shiny_hues=(6, 37),
        description="H:47->23 (diff=24)",
    ),  # #010
    "metapod": PaletteEntry(
        normal_hues=(34, 49),
        shiny_hues=(0, 20),
        description="H:44->5 (diff=39)",
    ),  # #011
    "butterfree": PaletteEntry(
        normal_hues=(115, 125),
        shiny_hues=(127, 155),
        description="H:120->150 (diff=30)",
    ),  # #012
    "weedle": PaletteEntry(
        normal_hues=(0, 24),
        shiny_hues=(12, 33),
        subtle=True,
        description="H:19->22 (diff=3)",
    ),  # #013
    "kakuna": PaletteEntry(
        normal_hues=(18, 31),
        shiny_hues=(28, 44),
        subtle=True,
        description="H:26->35 (diff=9)",
    ),  # #014
    "beedrill": PaletteEntry(
        normal_hues=(127, 145),
        shiny_hues=(127, 145),
        subtle=True,
        description="H:140->140 (diff=0)",
    ),  # #015
    "pidgey": PaletteEntry(
        normal_hues=(5, 31),
        shiny_hues=(18, 35),
        subtle=True,
        description="H:24->30 (diff=6)",
    ),  # #016
    "pidgeotto": PaletteEntry(
        normal_hues=(0, 35),
        shiny_hues=(16, 35),
        description="H:10->23 (diff=13)",
    ),  # #017
    "pidgeot": PaletteEntry(
        normal_hues=(5, 33),
        shiny_hues=(8, 31),
        subtle=True,
        description="H:28->22 (diff=6)",
    ),  # #018
    "rattata": PaletteEntry(
        normal_hues=(139, 165),
        shiny_hues=(19, 31),
        description="H:144->24 (diff=60)",
    ),  # #019
    "raticate": PaletteEntry(
        normal_hues=(3, 35),
        shiny_hues=(3, 16),
        description="H:19->9 (diff=10)",
    ),  # #020
    "spearow": PaletteEntry(
        normal_hues=(0, 179),
        shiny_hues=(8, 35),
        subtle=True,
        description="H:19->26 (diff=7)",
    ),  # #021
    "fearow": PaletteEntry(
        normal_hues=(6, 25),
        shiny_hues=(14, 33),
        subtle=True,
        description="H:19->27 (diff=8)",
    ),  # #022
    "ekans": PaletteEntry(
        normal_hues=(152, 168),
        shiny_hues=(13, 31),
        description="H:159->26 (diff=47)",
    ),  # #023
    "arbok": PaletteEntry(
        normal_hues=(151, 168),
        shiny_hues=(13, 27),
        description="H:159->19 (diff=40)",
    ),  # #024
    "pikachu": PaletteEntry(
        normal_hues=(14, 33),
        shiny_hues=(9, 29),
        subtle=True,
        description="H:28->24 (diff=4)",
    ),  # #025
    "raichu": PaletteEntry(
        normal_hues=(6, 31),
        shiny_hues=(6, 27),
        subtle=True,
        description="H:17->13 (diff=4)",
    ),  # #026
    "sandshrew": PaletteEntry(
        normal_hues=(10, 34),
        shiny_hues=(27, 43),
        description="H:26->36 (diff=10)",
    ),  # #027
    "sandslash": PaletteEntry(
        normal_hues=(14, 31),
        shiny_hues=(1, 30),
        subtle=True,
        description="H:20->25 (diff=5)",
    ),  # #028
    "nidoran_f": PaletteEntry(
        normal_hues=(76, 109),
        shiny_hues=(132, 142),
        description="H:96->137 (diff=41)",
    ),  # #029
    "nidorina": PaletteEntry(
        normal_hues=(89, 114),
        shiny_hues=(149, 172),
        description="H:96->154 (diff=58)",
    ),  # #030
    "nidoqueen": PaletteEntry(
        normal_hues=(89, 110),
        shiny_hues=(21, 35),
        description="H:105->26 (diff=79)",
    ),  # #031
    "nidoran_m": PaletteEntry(
        normal_hues=(139, 162),
        shiny_hues=(97, 117),
        description="H:150->108 (diff=42)",
    ),  # #032
    "nidorino": PaletteEntry(
        normal_hues=(136, 162),
        shiny_hues=(97, 117),
        description="H:143->108 (diff=35)",
    ),  # #033
    "nidoking": PaletteEntry(
        normal_hues=(138, 158),
        shiny_hues=(94, 115),
        description="H:153->107 (diff=46)",
    ),  # #034
    "clefairy": PaletteEntry(
        normal_hues=(0, 16),
        shiny_hues=(153, 163),
        description="H:11->158 (diff=33)",
    ),  # #035
    "clefable": PaletteEntry(
        normal_hues=(0, 12),
        shiny_hues=(153, 163),
        description="H:0->158 (diff=22)",
    ),  # #036
    "vulpix": PaletteEntry(
        normal_hues=(0, 21),
        shiny_hues=(18, 34),
        description="H:10->29 (diff=19)",
    ),  # #037
    "ninetales": PaletteEntry(
        normal_hues=(11, 31),
        shiny_hues=(3, 175),
        description="H:22->170 (diff=32)",
    ),  # #038
    "jigglypuff": PaletteEntry(
        normal_hues=(0, 9),
        shiny_hues=(154, 170),
        description="H:0->165 (diff=15)",
    ),  # #039
    "wigglytuff": PaletteEntry(
        normal_hues=(0, 14),
        shiny_hues=(145, 165),
        description="H:0->160 (diff=20)",
    ),  # #040
    "zubat": PaletteEntry(
        normal_hues=(103, 129),
        shiny_hues=(37, 52),
        description="H:108->42 (diff=66)",
    ),  # #041
    "golbat": PaletteEntry(
        normal_hues=(150, 163),
        shiny_hues=(0, 8),
        description="H:155->2 (diff=27)",
    ),  # #042
    "oddish": PaletteEntry(
        normal_hues=(34, 49),
        shiny_hues=(31, 58),
        subtle=True,
        description="H:39->36 (diff=3)",
    ),  # #043
    "gloom": PaletteEntry(
        normal_hues=(98, 119),
        shiny_hues=(10, 39),
        description="H:110->34 (diff=76)",
    ),  # #044
    "vileplume": PaletteEntry(
        normal_hues=(0, 179),
        shiny_hues=(8, 31),
        description="H:0->20 (diff=20)",
    ),  # #045
    "paras": PaletteEntry(
        normal_hues=(0, 23),
        shiny_hues=(6, 29),
        subtle=True,
        description="H:14->14 (diff=0)",
    ),  # #046
    "parasect": PaletteEntry(
        normal_hues=(0, 179),
        shiny_hues=(10, 34),
        description="H:0->18 (diff=18)",
    ),  # #047
    "venonat": PaletteEntry(
        normal_hues=(125, 148),
        shiny_hues=(138, 150),
        subtle=True,
        description="H:143->143 (diff=0)",
    ),  # #048
    "venomoth": PaletteEntry(
        normal_hues=(130, 150),
        shiny_hues=(98, 115),
        description="H:143->103 (diff=40)",
    ),  # #049
    "diglett": PaletteEntry(
        normal_hues=(3, 31),
        shiny_hues=(8, 31),
        description="H:26->13 (diff=13)",
    ),  # #050
    "dugtrio": PaletteEntry(
        normal_hues=(0, 35),
        shiny_hues=(4, 35),
        subtle=True,
        description="H:13->13 (diff=0)",
    ),  # #051
    "meowth": PaletteEntry(
        normal_hues=(8, 35),
        shiny_hues=(1, 30),
        subtle=True,
        description="H:21->18 (diff=3)",
    ),  # #052
    "persian": PaletteEntry(
        normal_hues=(14, 35),
        shiny_hues=(17, 32),
        subtle=True,
        description="H:24->26 (diff=2)",
    ),  # #053
    "psyduck": PaletteEntry(
        normal_hues=(12, 28),
        shiny_hues=(85, 98),
        description="H:23->93 (diff=70)",
    ),  # #054
    "golduck": PaletteEntry(
        normal_hues=(98, 125),
        shiny_hues=(96, 111),
        description="H:120->103 (diff=17)",
    ),  # #055
    "mankey": PaletteEntry(
        normal_hues=(7, 30),
        shiny_hues=(13, 41),
        description="H:19->36 (diff=17)",
    ),  # #056
    "primeape": PaletteEntry(
        normal_hues=(8, 25),
        shiny_hues=(8, 33),
        subtle=True,
        description="H:16->16 (diff=0)",
    ),  # #057
    "growlithe": PaletteEntry(
        normal_hues=(4, 32),
        shiny_hues=(17, 32),
        subtle=True,
        description="H:24->25 (diff=1)",
    ),  # #058
    "arcanine": PaletteEntry(
        normal_hues=(0, 35),
        shiny_hues=(10, 28),
        subtle=True,
        description="H:20->17 (diff=3)",
    ),  # #059
    "poliwag": PaletteEntry(
        normal_hues=(103, 121),
        shiny_hues=(96, 109),
        description="H:115->102 (diff=13)",
    ),  # #060
    "poliwhirl": PaletteEntry(
        normal_hues=(104, 120),
        shiny_hues=(93, 108),
        description="H:115->99 (diff=16)",
    ),  # #061
    "poliwrath": PaletteEntry(
        normal_hues=(97, 125),
        shiny_hues=(46, 56),
        description="H:109->51 (diff=58)",
    ),  # #062
    "abra": PaletteEntry(
        normal_hues=(10, 35),
        shiny_hues=(6, 33),
        subtle=True,
        description="H:27->21 (diff=6)",
    ),  # #063
    "kadabra": PaletteEntry(
        normal_hues=(11, 35),
        shiny_hues=(0, 35),
        subtle=True,
        description="H:25->20 (diff=5)",
    ),  # #064
    "alakazam": PaletteEntry(
        normal_hues=(12, 33),
        shiny_hues=(3, 29),
        subtle=True,
        description="H:28->24 (diff=4)",
    ),  # #065
    "machop": PaletteEntry(
        normal_hues=(63, 75),
        shiny_hues=(18, 37),
        description="H:70->23 (diff=47)",
    ),  # #066
    "machoke": PaletteEntry(
        normal_hues=(115, 133),
        shiny_hues=(27, 39),
        description="H:125->34 (diff=89)",
    ),  # #067
    "machamp": PaletteEntry(
        normal_hues=(55, 73),
        shiny_hues=(27, 43),
        description="H:66->38 (diff=28)",
    ),  # #068
    "bellsprout": PaletteEntry(
        normal_hues=(21, 49),
        shiny_hues=(13, 44),
        description="H:44->24 (diff=20)",
    ),  # #069
    "weepinbell": PaletteEntry(
        normal_hues=(34, 49),
        shiny_hues=(25, 44),
        subtle=True,
        description="H:44->36 (diff=8)",
    ),  # #070
    "victreebel": PaletteEntry(
        normal_hues=(34, 49),
        shiny_hues=(13, 40),
        description="H:44->24 (diff=20)",
    ),  # #071
    "tentacool": PaletteEntry(
        normal_hues=(80, 110),
        shiny_hues=(115, 125),
        description="H:102->120 (diff=18)",
    ),  # #072
    "tentacruel": PaletteEntry(
        normal_hues=(18, 35),
        shiny_hues=(98, 108),
        description="H:30->103 (diff=73)",
    ),  # #073
    "geodude": PaletteEntry(
        normal_hues=(28, 41),
        shiny_hues=(13, 28),
        description="H:33->23 (diff=10)",
    ),  # #074
    "graveler": PaletteEntry(
        normal_hues=(21, 45),
        shiny_hues=(4, 25),
        description="H:40->20 (diff=20)",
    ),  # #075
    "golem": PaletteEntry(
        normal_hues=(17, 44),
        shiny_hues=(5, 20),
        description="H:33->15 (diff=18)",
    ),  # #076
    "ponyta": PaletteEntry(
        normal_hues=(7, 32),
        shiny_hues=(14, 35),
        subtle=True,
        description="H:26->26 (diff=0)",
    ),  # #077
    "rapidash": PaletteEntry(
        normal_hues=(0, 32),
        shiny_hues=(108, 118),
        description="H:12->113 (diff=79)",
    ),  # #078
    "slowpoke": PaletteEntry(
        normal_hues=(0, 179),
        shiny_hues=(0, 178),
        subtle=True,
        description="H:176->171 (diff=5)",
    ),  # #079
    "slowbro": PaletteEntry(
        normal_hues=(0, 28),
        shiny_hues=(119, 137),
        description="H:7->124 (diff=63)",
    ),  # #080
    "magnemite": PaletteEntry(
        normal_hues=(0, 5),
        shiny_hues=(25, 35),
        description="H:0->30 (diff=30)",
    ),  # #081
    "magneton": PaletteEntry(
        normal_hues=(0, 179),
        shiny_hues=(0, 23),
        description="H:0->18 (diff=18)",
    ),  # #082
    "farfetchd": PaletteEntry(
        normal_hues=(10, 51),
        shiny_hues=(0, 23),
        description="H:30->3 (diff=27)",
    ),  # #083
    "doduo": PaletteEntry(
        normal_hues=(7, 31),
        shiny_hues=(18, 38),
        description="H:16->32 (diff=16)",
    ),  # #084
    "dodrio": PaletteEntry(
        normal_hues=(10, 28),
        shiny_hues=(16, 38),
        description="H:15->32 (diff=17)",
    ),  # #085
    "seel": PaletteEntry(
        normal_hues=(115, 125),
        shiny_hues=(1, 35),
        description="H:120->20 (diff=80)",
    ),  # #086
    "dewgong": PaletteEntry(
        normal_hues=(108, 119),
        shiny_hues=(15, 25),
        description="H:114->20 (diff=86)",
    ),  # #087
    "grimer": PaletteEntry(
        normal_hues=(134, 167),
        shiny_hues=(38, 50),
        description="H:145->43 (diff=78)",
    ),  # #088
    "muk": PaletteEntry(
        normal_hues=(140, 167),
        shiny_hues=(43, 53),
        description="H:162->48 (diff=66)",
    ),  # #089
    "shellder": PaletteEntry(
        normal_hues=(105, 115),
        shiny_hues=(2, 23),
        description="H:110->14 (diff=84)",
    ),  # #090
    "cloyster": PaletteEntry(
        normal_hues=(136, 150),
        shiny_hues=(100, 111),
        description="H:143->105 (diff=38)",
    ),  # #091
    "gastly": PaletteEntry(
        normal_hues=(139, 161),
        shiny_hues=(95, 105),
        description="H:156->100 (diff=56)",
    ),  # #092
    "haunter": PaletteEntry(
        normal_hues=(125, 145),
        shiny_hues=(132, 152),
        description="H:137->147 (diff=10)",
    ),  # #093
    "gengar": PaletteEntry(
        normal_hues=(145, 170),
        shiny_hues=(115, 125),
        description="H:165->120 (diff=45)",
    ),  # #094
    "onix": PaletteEntry(
        normal_hues=(35, 45),
        shiny_hues=(25, 35),
        description="H:40->30 (diff=10)",
    ),  # #095
    "drowzee": PaletteEntry(
        normal_hues=(10, 30),
        shiny_hues=(3, 179),
        description="H:25->168 (diff=37)",
    ),  # #096
    "hypno": PaletteEntry(
        normal_hues=(14, 30),
        shiny_hues=(0, 175),
        description="H:23->170 (diff=33)",
    ),  # #097
    "krabby": PaletteEntry(
        normal_hues=(0, 26),
        shiny_hues=(16, 30),
        subtle=True,
        description="H:21->21 (diff=0)",
    ),  # #098
    "kingler": PaletteEntry(
        normal_hues=(0, 26),
        shiny_hues=(23, 45),
        description="H:10->34 (diff=24)",
    ),  # #099
    "voltorb": PaletteEntry(
        normal_hues=(0, 14),
        shiny_hues=(110, 125),
        description="H:0->115 (diff=65)",
    ),  # #100
    "electrode": PaletteEntry(
        normal_hues=(0, 14),
        shiny_hues=(97, 125),
        description="H:8->102 (diff=86)",
    ),  # #101
    "exeggcute": PaletteEntry(
        normal_hues=(2, 18),
        shiny_hues=(13, 35),
        description="H:8->28 (diff=20)",
    ),  # #102
    "exeggutor": PaletteEntry(
        normal_hues=(34, 49),
        shiny_hues=(6, 28),
        description="H:44->23 (diff=21)",
    ),  # #103
    "cubone": PaletteEntry(
        normal_hues=(8, 35),
        shiny_hues=(16, 39),
        subtle=True,
        description="H:30->30 (diff=0)",
    ),  # #104
    "marowak": PaletteEntry(
        normal_hues=(8, 35),
        shiny_hues=(8, 38),
        description="H:17->33 (diff=16)",
    ),  # #105
    "hitmonlee": PaletteEntry(
        normal_hues=(0, 35),
        shiny_hues=(10, 41),
        description="H:13->32 (diff=19)",
    ),  # #106
    "hitmonchan": PaletteEntry(
        normal_hues=(1, 27),
        shiny_hues=(23, 33),
        subtle=True,
        description="H:21->28 (diff=7)",
    ),  # #107
    "lickitung": PaletteEntry(
        normal_hues=(0, 31),
        shiny_hues=(16, 35),
        description="H:8->25 (diff=17)",
    ),  # #108
    "koffing": PaletteEntry(
        normal_hues=(19, 33),
        shiny_hues=(76, 95),
        description="H:24->90 (diff=66)",
    ),  # #109
    "weezing": PaletteEntry(
        normal_hues=(162, 174),
        shiny_hues=(80, 95),
        description="H:167->90 (diff=77)",
    ),  # #110
    "rhyhorn": PaletteEntry(
        normal_hues=(115, 125),
        shiny_hues=(2, 14),
        description="H:120->9 (diff=69)",
    ),  # #111
    "rhydon": PaletteEntry(
        normal_hues=(0, 28),
        shiny_hues=(15, 28),
        subtle=True,
        description="H:23->20 (diff=3)",
    ),  # #112
    "chansey": PaletteEntry(
        normal_hues=(0, 178),
        shiny_hues=(13, 26),
        description="H:0->20 (diff=20)",
    ),  # #113
    "tangela": PaletteEntry(
        normal_hues=(94, 105),
        shiny_hues=(43, 65),
        description="H:99->48 (diff=51)",
    ),  # #114
    "kangaskhan": PaletteEntry(
        normal_hues=(6, 33),
        shiny_hues=(16, 42),
        description="H:11->26 (diff=15)",
    ),  # #115
    "horsea": PaletteEntry(
        normal_hues=(97, 115),
        shiny_hues=(88, 99),
        description="H:110->93 (diff=17)",
    ),  # #116
    "seadra": PaletteEntry(
        normal_hues=(89, 110),
        shiny_hues=(98, 125),
        subtle=True,
        description="H:105->109 (diff=4)",
    ),  # #117
    "goldeen": PaletteEntry(
        normal_hues=(0, 22),
        shiny_hues=(3, 31),
        subtle=True,
        description="H:10->18 (diff=8)",
    ),  # #118
    "seaking": PaletteEntry(
        normal_hues=(0, 14),
        shiny_hues=(16, 44),
        description="H:6->36 (diff=30)",
    ),  # #119
    "staryu": PaletteEntry(
        normal_hues=(1, 31),
        shiny_hues=(19, 35),
        description="H:17->30 (diff=13)",
    ),  # #120
    "starmie": PaletteEntry(
        normal_hues=(136, 155),
        shiny_hues=(98, 109),
        description="H:143->104 (diff=39)",
    ),  # #121
    "mr_mime": PaletteEntry(
        normal_hues=(0, 10),
        shiny_hues=(35, 51),
        description="H:4->40 (diff=36)",
    ),  # #122
    "scyther": PaletteEntry(
        normal_hues=(20, 51),
        shiny_hues=(25, 54),
        subtle=True,
        description="H:43->49 (diff=6)",
    ),  # #123
    "jynx": PaletteEntry(
        normal_hues=(0, 7),
        shiny_hues=(154, 171),
        description="H:0->166 (diff=14)",
    ),  # #124
    "electabuzz": PaletteEntry(
        normal_hues=(15, 35),
        shiny_hues=(3, 28),
        subtle=True,
        description="H:23->17 (diff=6)",
    ),  # #125
    "magmar": PaletteEntry(
        normal_hues=(0, 33),
        shiny_hues=(165, 179),
        description="H:21->178 (diff=23)",
    ),  # #126
    "pinsir": PaletteEntry(
        normal_hues=(8, 35),
        shiny_hues=(110, 122),
        description="H:30->115 (diff=85)",
    ),  # #127
    "tauros": PaletteEntry(
        normal_hues=(11, 27),
        shiny_hues=(16, 50),
        subtle=True,
        description="H:16->25 (diff=9)",
    ),  # #128
    "magikarp": PaletteEntry(
        normal_hues=(0, 17),
        shiny_hues=(6, 39),
        description="H:0->26 (diff=26)",
    ),  # #129
    "gyarados": PaletteEntry(
        normal_hues=(102, 125),
        shiny_hues=(0, 25),
        description="H:114->8 (diff=74)",
    ),  # #130
    "lapras": PaletteEntry(
        normal_hues=(5, 30),
        shiny_hues=(122, 136),
        description="H:25->127 (diff=78)",
    ),  # #131
    "ditto": PaletteEntry(
        normal_hues=(154, 170),
        shiny_hues=(94, 109),
        description="H:159->99 (diff=60)",
    ),  # #132
    "eevee": PaletteEntry(
        normal_hues=(11, 31),
        shiny_hues=(103, 119),
        description="H:17->108 (diff=89)",
    ),  # #133
    "vaporeon": PaletteEntry(
        normal_hues=(77, 88),
        shiny_hues=(138, 166),
        description="H:83->146 (diff=63)",
    ),  # #134
    "jolteon": PaletteEntry(
        normal_hues=(15, 33),
        shiny_hues=(31, 46),
        description="H:25->36 (diff=11)",
    ),  # #135
    "flareon": PaletteEntry(
        normal_hues=(4, 32),
        shiny_hues=(8, 35),
        subtle=True,
        description="H:27->20 (diff=7)",
    ),  # #136
    "porygon": PaletteEntry(
        normal_hues=(81, 104),
        shiny_hues=(135, 155),
        description="H:99->150 (diff=51)",
    ),  # #137
    "omanyte": PaletteEntry(
        normal_hues=(22, 35),
        shiny_hues=(16, 33),
        subtle=True,
        description="H:28->23 (diff=5)",
    ),  # #138
    "omastar": PaletteEntry(
        normal_hues=(82, 92),
        shiny_hues=(25, 38),
        description="H:87->32 (diff=55)",
    ),  # #139
    "kabuto": PaletteEntry(
        normal_hues=(10, 29),
        shiny_hues=(19, 47),
        description="H:20->40 (diff=20)",
    ),  # #140
    "kabutops": PaletteEntry(
        normal_hues=(16, 28),
        shiny_hues=(31, 44),
        description="H:21->37 (diff=16)",
    ),  # #141
    "aerodactyl": PaletteEntry(
        normal_hues=(93, 103),
        shiny_hues=(142, 160),
        description="H:98->150 (diff=52)",
    ),  # #142
    "snorlax": PaletteEntry(
        normal_hues=(11, 35),
        shiny_hues=(11, 31),
        subtle=True,
        description="H:30->23 (diff=7)",
    ),  # #143
    "articuno": PaletteEntry(
        normal_hues=(100, 125),
        shiny_hues=(100, 115),
        subtle=True,
        description="H:106->105 (diff=1)",
    ),  # #144
    "zapdos": PaletteEntry(
        normal_hues=(13, 35),
        shiny_hues=(0, 33),
        subtle=True,
        description="H:28->23 (diff=5)",
    ),  # #145
    "moltres": PaletteEntry(
        normal_hues=(7, 34),
        shiny_hues=(0, 23),
        description="H:26->2 (diff=24)",
    ),  # #146
    "dratini": PaletteEntry(
        normal_hues=(128, 140),
        shiny_hues=(25, 35),
        description="H:135->30 (diff=75)",
    ),  # #147
    "dragonair": PaletteEntry(
        normal_hues=(96, 116),
        shiny_hues=(139, 161),
        description="H:105->153 (diff=48)",
    ),  # #148
    "dragonite": PaletteEntry(
        normal_hues=(16, 35),
        shiny_hues=(20, 65),
        description="H:22->42 (diff=20)",
    ),  # #149
    "mewtwo": PaletteEntry(
        normal_hues=(125, 155),
        shiny_hues=(40, 85),
        min_sat=120,
        min_val=80,
        description="Purple tail (H~139) -> green tail (H~44-46), hand-calibrated",
    ),  # #150
    "mew": PaletteEntry(
        normal_hues=(0, 179),
        shiny_hues=(94, 114),
        description="H:5->99 (diff=86)",
    ),  # #151
    "chikorita": PaletteEntry(
        normal_hues=(32, 60),
        shiny_hues=(11, 35),
        subtle=True,
        description="H:37->28 (diff=9)",
    ),  # #152
    "bayleef": PaletteEntry(
        normal_hues=(18, 53),
        shiny_hues=(3, 29),
        description="H:28->13 (diff=15)",
    ),  # #153
    "meganium": PaletteEntry(
        normal_hues=(21, 61),
        shiny_hues=(6, 33),
        description="H:45->28 (diff=17)",
    ),  # #154
    "cyndaquil": PaletteEntry(
        normal_hues=(0, 31),
        shiny_hues=(0, 31),
        subtle=True,
        description="H:12->12 (diff=0)",
    ),  # #155
    "quilava": PaletteEntry(
        normal_hues=(7, 31),
        shiny_hues=(3, 31),
        subtle=True,
        description="H:25->25 (diff=0)",
    ),  # #156
    "typhlosion": PaletteEntry(
        normal_hues=(16, 31),
        shiny_hues=(10, 31),
        subtle=True,
        description="H:25->25 (diff=0)",
    ),  # #157
    "totodile": PaletteEntry(
        normal_hues=(97, 125),
        shiny_hues=(66, 88),
        description="H:102->83 (diff=19)",
    ),  # #158
    "croconaw": PaletteEntry(
        normal_hues=(97, 125),
        shiny_hues=(76, 106),
        description="H:102->88 (diff=14)",
    ),  # #159
    "feraligatr": PaletteEntry(
        normal_hues=(97, 125),
        shiny_hues=(81, 109),
        description="H:102->88 (diff=14)",
    ),  # #160
    "sentret": PaletteEntry(
        normal_hues=(0, 30),
        shiny_hues=(16, 32),
        subtle=True,
        description="H:23->26 (diff=3)",
    ),  # #161
    "furret": PaletteEntry(
        normal_hues=(4, 30),
        shiny_hues=(3, 176),
        description="H:25->8 (diff=17)",
    ),  # #162
    "hoothoot": PaletteEntry(
        normal_hues=(8, 39),
        shiny_hues=(8, 35),
        subtle=True,
        description="H:25->18 (diff=7)",
    ),  # #163
    "noctowl": PaletteEntry(
        normal_hues=(5, 35),
        shiny_hues=(14, 38),
        subtle=True,
        description="H:10->19 (diff=9)",
    ),  # #164
    "ledyba": PaletteEntry(
        normal_hues=(0, 31),
        shiny_hues=(10, 33),
        description="H:8->28 (diff=20)",
    ),  # #165
    "ledian": PaletteEntry(
        normal_hues=(2, 31),
        shiny_hues=(10, 33),
        description="H:8->19 (diff=11)",
    ),  # #166
    "spinarak": PaletteEntry(
        normal_hues=(21, 52),
        shiny_hues=(91, 115),
        description="H:45->100 (diff=55)",
    ),  # #167
    "ariados": PaletteEntry(
        normal_hues=(2, 32),
        shiny_hues=(97, 115),
        description="H:12->110 (diff=82)",
    ),  # #168
    "crobat": PaletteEntry(
        normal_hues=(137, 153),
        shiny_hues=(164, 179),
        description="H:148->173 (diff=25)",
    ),  # #169
    "chinchou": PaletteEntry(
        normal_hues=(100, 121),
        shiny_hues=(90, 116),
        subtle=True,
        description="H:113->106 (diff=7)",
    ),  # #170
    "lanturn": PaletteEntry(
        normal_hues=(97, 116),
        shiny_hues=(130, 148),
        description="H:111->136 (diff=25)",
    ),  # #171
    "pichu": PaletteEntry(
        normal_hues=(2, 35),
        shiny_hues=(14, 35),
        subtle=True,
        description="H:26->25 (diff=1)",
    ),  # #172
    "cleffa": PaletteEntry(
        normal_hues=(3, 25),
        shiny_hues=(0, 179),
        description="H:15->0 (diff=15)",
    ),  # #173
    "igglybuff": PaletteEntry(
        normal_hues=(0, 20),
        shiny_hues=(157, 178),
        description="H:15->162 (diff=33)",
    ),  # #174
    "togepi": PaletteEntry(
        normal_hues=(0, 35),
        shiny_hues=(11, 35),
        subtle=True,
        description="H:23->21 (diff=2)",
    ),  # #175
    "togetic": PaletteEntry(
        normal_hues=(109, 125),
        shiny_hues=(15, 33),
        description="H:120->26 (diff=86)",
    ),  # #176
    "natu": PaletteEntry(
        normal_hues=(39, 63),
        shiny_hues=(17, 47),
        description="H:58->41 (diff=17)",
    ),  # #177
    "xatu": PaletteEntry(
        normal_hues=(39, 63),
        shiny_hues=(20, 47),
        description="H:58->42 (diff=16)",
    ),  # #178
    "mareep": PaletteEntry(
        normal_hues=(12, 31),
        shiny_hues=(0, 178),
        description="H:26->5 (diff=21)",
    ),  # #179
    "flaaffy": PaletteEntry(
        normal_hues=(99, 125),
        shiny_hues=(160, 179),
        description="H:120->171 (diff=51)",
    ),  # #180
    "ampharos": PaletteEntry(
        normal_hues=(5, 32),
        shiny_hues=(158, 172),
        description="H:27->165 (diff=42)",
    ),  # #181
    "bellossom": PaletteEntry(
        normal_hues=(8, 53),
        shiny_hues=(31, 44),
        subtle=True,
        description="H:30->36 (diff=6)",
    ),  # #182
    "marill": PaletteEntry(
        normal_hues=(103, 118),
        shiny_hues=(55, 72),
        description="H:112->62 (diff=50)",
    ),  # #183
    "azumarill": PaletteEntry(
        normal_hues=(97, 125),
        shiny_hues=(11, 32),
        description="H:102->24 (diff=78)",
    ),  # #184
    "sudowoodo": PaletteEntry(
        normal_hues=(15, 27),
        shiny_hues=(25, 39),
        description="H:21->34 (diff=13)",
    ),  # #185
    "politoed": PaletteEntry(
        normal_hues=(17, 53),
        shiny_hues=(93, 113),
        description="H:42->103 (diff=61)",
    ),  # #186
    "hoppip": PaletteEntry(
        normal_hues=(0, 14),
        shiny_hues=(34, 59),
        description="H:3->43 (diff=40)",
    ),  # #187
    "skiploom": PaletteEntry(
        normal_hues=(41, 58),
        shiny_hues=(154, 167),
        description="H:53->159 (diff=74)",
    ),  # #188
    "jumpluff": PaletteEntry(
        normal_hues=(18, 35),
        shiny_hues=(145, 175),
        description="H:25->155 (diff=50)",
    ),  # #189
    "aipom": PaletteEntry(
        normal_hues=(134, 145),
        shiny_hues=(0, 179),
        description="H:140->169 (diff=29)",
    ),  # #190
    "sunkern": PaletteEntry(
        normal_hues=(19, 48),
        shiny_hues=(7, 47),
        subtle=True,
        description="H:26->23 (diff=3)",
    ),  # #191
    "sunflora": PaletteEntry(
        normal_hues=(21, 49),
        shiny_hues=(19, 35),
        description="H:42->28 (diff=14)",
    ),  # #192
    "yanma": PaletteEntry(
        normal_hues=(4, 26),
        shiny_hues=(90, 115),
        description="H:9->102 (diff=87)",
    ),  # #193
    "wooper": PaletteEntry(
        normal_hues=(85, 116),
        shiny_hues=(0, 179),
        description="H:104->175 (diff=71)",
    ),  # #194
    "quagsire": PaletteEntry(
        normal_hues=(95, 115),
        shiny_hues=(138, 163),
        description="H:105->150 (diff=45)",
    ),  # #195
    "espeon": PaletteEntry(
        normal_hues=(128, 146),
        shiny_hues=(39, 65),
        description="H:137->53 (diff=84)",
    ),  # #196
    "umbreon": PaletteEntry(
        normal_hues=(0, 25),
        shiny_hues=(0, 5),
        subtle=True,
        description="H:0->0 (diff=0)",
    ),  # #197
    "murkrow": PaletteEntry(
        normal_hues=(85, 95),
        shiny_hues=(149, 167),
        description="H:90->155 (diff=65)",
    ),  # #198
    "slowking": PaletteEntry(
        normal_hues=(2, 35),
        shiny_hues=(163, 178),
        description="H:10->172 (diff=18)",
    ),  # #199
    "misdreavus": PaletteEntry(
        normal_hues=(78, 101),
        shiny_hues=(4, 31),
        description="H:84->26 (diff=58)",
    ),  # #200
    # 201 unown: insufficient colored pixels
    "wobbuffet": PaletteEntry(
        normal_hues=(91, 104),
        shiny_hues=(149, 169),
        description="H:99->154 (diff=55)",
    ),  # #202
    "girafarig": PaletteEntry(
        normal_hues=(10, 30),
        shiny_hues=(10, 27),
        subtle=True,
        description="H:23->15 (diff=8)",
    ),  # #203
    "pineco": PaletteEntry(
        normal_hues=(85, 113),
        shiny_hues=(0, 29),
        description="H:104->4 (diff=80)",
    ),  # #204
    "forretress": PaletteEntry(
        normal_hues=(145, 176),
        shiny_hues=(8, 33),
        description="H:154->23 (diff=49)",
    ),  # #205
    "dunsparce": PaletteEntry(
        normal_hues=(16, 35),
        shiny_hues=(7, 35),
        subtle=True,
        description="H:30->30 (diff=0)",
    ),  # #206
    "gligar": PaletteEntry(
        normal_hues=(125, 148),
        shiny_hues=(105, 121),
        description="H:138->111 (diff=27)",
    ),  # #207
    "steelix": PaletteEntry(
        normal_hues=(97, 125),
        shiny_hues=(8, 29),
        description="H:102->20 (diff=82)",
    ),  # #208
    "snubbull": PaletteEntry(
        normal_hues=(0, 179),
        shiny_hues=(2, 178),
        subtle=True,
        description="H:178->173 (diff=5)",
    ),  # #209
    "granbull": PaletteEntry(
        normal_hues=(138, 163),
        shiny_hues=(8, 22),
        description="H:150->17 (diff=47)",
    ),  # #210
    "qwilfish": PaletteEntry(
        normal_hues=(101, 120),
        shiny_hues=(150, 164),
        description="H:115->155 (diff=40)",
    ),  # #211
    "scizor": PaletteEntry(
        normal_hues=(3, 23),
        shiny_hues=(27, 40),
        description="H:10->32 (diff=22)",
    ),  # #212
    "shuckle": PaletteEntry(
        normal_hues=(2, 28),
        shiny_hues=(15, 35),
        description="H:8->30 (diff=22)",
    ),  # #213
    "heracross": PaletteEntry(
        normal_hues=(108, 122),
        shiny_hues=(145, 164),
        description="H:115->153 (diff=38)",
    ),  # #214
    "sneasel": PaletteEntry(
        normal_hues=(55, 83),
        shiny_hues=(163, 175),
        description="H:75->168 (diff=87)",
    ),  # #215
    "teddiursa": PaletteEntry(
        normal_hues=(11, 32),
        shiny_hues=(22, 54),
        description="H:16->45 (diff=29)",
    ),  # #216
    "ursaring": PaletteEntry(
        normal_hues=(15, 28),
        shiny_hues=(34, 51),
        description="H:21->44 (diff=23)",
    ),  # #217
    "slugma": PaletteEntry(
        normal_hues=(2, 26),
        shiny_hues=(15, 30),
        description="H:9->21 (diff=12)",
    ),  # #218
    "magcargo": PaletteEntry(
        normal_hues=(2, 26),
        shiny_hues=(132, 162),
        description="H:9->150 (diff=39)",
    ),  # #219
    "swinub": PaletteEntry(
        normal_hues=(16, 28),
        shiny_hues=(95, 125),
        description="H:21->100 (diff=79)",
    ),  # #220
    "piloswine": PaletteEntry(
        normal_hues=(16, 28),
        shiny_hues=(16, 33),
        subtle=True,
        description="H:21->28 (diff=7)",
    ),  # #221
    "corsola": PaletteEntry(
        normal_hues=(0, 179),
        shiny_hues=(90, 113),
        description="H:171->101 (diff=70)",
    ),  # #222
    "remoraid": PaletteEntry(
        normal_hues=(79, 106),
        shiny_hues=(140, 155),
        description="H:84->145 (diff=61)",
    ),  # #223
    "octillery": PaletteEntry(
        normal_hues=(0, 25),
        shiny_hues=(10, 40),
        description="H:6->21 (diff=15)",
    ),  # #224
    "delibird": PaletteEntry(
        normal_hues=(4, 27),
        shiny_hues=(150, 167),
        description="H:9->162 (diff=27)",
    ),  # #225
    "mantine": PaletteEntry(
        normal_hues=(100, 119),
        shiny_hues=(98, 119),
        subtle=True,
        description="H:107->105 (diff=2)",
    ),  # #226
    "skarmory": PaletteEntry(
        normal_hues=(0, 13),
        shiny_hues=(15, 35),
        description="H:2->20 (diff=18)",
    ),  # #227
    "houndour": PaletteEntry(
        normal_hues=(0, 24),
        shiny_hues=(98, 112),
        description="H:0->105 (diff=75)",
    ),  # #228
    "houndoom": PaletteEntry(
        normal_hues=(0, 24),
        shiny_hues=(105, 120),
        description="H:0->115 (diff=65)",
    ),  # #229
    "kingdra": PaletteEntry(
        normal_hues=(94, 114),
        shiny_hues=(134, 155),
        description="H:99->141 (diff=42)",
    ),  # #230
    "phanpy": PaletteEntry(
        normal_hues=(96, 125),
        shiny_hues=(93, 116),
        subtle=True,
        description="H:108->101 (diff=7)",
    ),  # #231
    "donphan": PaletteEntry(
        normal_hues=(85, 95),
        shiny_hues=(8, 35),
        description="H:90->30 (diff=60)",
    ),  # #232
    "porygon2": PaletteEntry(
        normal_hues=(0, 20),
        shiny_hues=(102, 115),
        description="H:4->110 (diff=74)",
    ),  # #233
    "stantler": PaletteEntry(
        normal_hues=(11, 35),
        shiny_hues=(14, 43),
        description="H:19->38 (diff=19)",
    ),  # #234
    "smeargle": PaletteEntry(
        normal_hues=(16, 35),
        shiny_hues=(0, 29),
        subtle=True,
        description="H:30->21 (diff=9)",
    ),  # #235
    "tyrogue": PaletteEntry(
        normal_hues=(139, 162),
        shiny_hues=(10, 28),
        description="H:144->20 (diff=56)",
    ),  # #236
    "hitmontop": PaletteEntry(
        normal_hues=(16, 30),
        shiny_hues=(6, 30),
        subtle=True,
        description="H:23->23 (diff=0)",
    ),  # #237
    "smoochum": PaletteEntry(
        normal_hues=(17, 32),
        shiny_hues=(18, 35),
        subtle=True,
        description="H:26->26 (diff=0)",
    ),  # #238
    "elekid": PaletteEntry(
        normal_hues=(13, 28),
        shiny_hues=(15, 31),
        subtle=True,
        description="H:23->24 (diff=1)",
    ),  # #239
    "magby": PaletteEntry(
        normal_hues=(0, 29),
        shiny_hues=(4, 33),
        subtle=True,
        description="H:5->14 (diff=9)",
    ),  # #240
    "miltank": PaletteEntry(
        normal_hues=(0, 28),
        shiny_hues=(100, 119),
        description="H:3->105 (diff=78)",
    ),  # #241
    "blissey": PaletteEntry(
        normal_hues=(166, 179),
        shiny_hues=(163, 179),
        subtle=True,
        description="H:171->168 (diff=3)",
    ),  # #242
    "raikou": PaletteEntry(
        normal_hues=(15, 30),
        shiny_hues=(11, 34),
        subtle=True,
        description="H:20->16 (diff=4)",
    ),  # #243
    "entei": PaletteEntry(
        normal_hues=(15, 28),
        shiny_hues=(0, 26),
        description="H:21->7 (diff=14)",
    ),  # #244
    "suicune": PaletteEntry(
        normal_hues=(93, 120),
        shiny_hues=(98, 116),
        subtle=True,
        description="H:105->106 (diff=1)",
    ),  # #245
    "larvitar": PaletteEntry(
        normal_hues=(55, 65),
        shiny_hues=(28, 41),
        description="H:60->33 (diff=27)",
    ),  # #246
    "pupitar": PaletteEntry(
        normal_hues=(96, 110),
        shiny_hues=(133, 151),
        description="H:105->138 (diff=33)",
    ),  # #247
    "tyranitar": PaletteEntry(
        normal_hues=(55, 65),
        shiny_hues=(10, 25),
        description="H:60->20 (diff=40)",
    ),  # #248
    "lugia": PaletteEntry(
        normal_hues=(99, 125),
        shiny_hues=(102, 118),
        description="H:120->108 (diff=12)",
    ),  # #249
    "ho_oh": PaletteEntry(
        normal_hues=(0, 32),
        shiny_hues=(0, 31),
        subtle=True,
        description="H:11->19 (diff=8)",
    ),  # #250
    "celebi": PaletteEntry(
        normal_hues=(37, 65),
        shiny_hues=(0, 179),
        description="H:60->178 (diff=62)",
    ),  # #251
    "treecko": PaletteEntry(
        normal_hues=(34, 49),
        shiny_hues=(80, 99),
        description="H:42->94 (diff=52)",
    ),  # #252
    "grovyle": PaletteEntry(
        normal_hues=(81, 102),
        shiny_hues=(0, 26),
        description="H:86->8 (diff=78)",
    ),  # #253
    "sceptile": PaletteEntry(
        normal_hues=(36, 54),
        shiny_hues=(80, 99),
        description="H:44->94 (diff=50)",
    ),  # #254
    "torchic": PaletteEntry(
        normal_hues=(1, 27),
        shiny_hues=(1, 29),
        description="H:8->23 (diff=15)",
    ),  # #255
    "combusken": PaletteEntry(
        normal_hues=(1, 27),
        shiny_hues=(0, 27),
        subtle=True,
        description="H:6->3 (diff=3)",
    ),  # #256
    "blaziken": PaletteEntry(
        normal_hues=(0, 27),
        shiny_hues=(0, 178),
        description="H:19->5 (diff=14)",
    ),  # #257
    "mudkip": PaletteEntry(
        normal_hues=(97, 125),
        shiny_hues=(138, 149),
        description="H:103->143 (diff=40)",
    ),  # #258
    "marshtomp": PaletteEntry(
        normal_hues=(115, 125),
        shiny_hues=(138, 148),
        description="H:120->143 (diff=23)",
    ),  # #259
    "swampert": PaletteEntry(
        normal_hues=(97, 121),
        shiny_hues=(121, 155),
        description="H:103->143 (diff=40)",
    ),  # #260
    "poochyena": PaletteEntry(
        normal_hues=(105, 125),
        shiny_hues=(8, 26),
        description="H:110->20 (diff=90)",
    ),  # #261
    "mightyena": PaletteEntry(
        normal_hues=(108, 125),
        shiny_hues=(8, 28),
        description="H:120->13 (diff=73)",
    ),  # #262
    "zigzagoon": PaletteEntry(
        normal_hues=(5, 28),
        shiny_hues=(3, 28),
        subtle=True,
        description="H:12->8 (diff=4)",
    ),  # #263
    "linoone": PaletteEntry(
        normal_hues=(8, 29),
        shiny_hues=(3, 29),
        description="H:13->24 (diff=11)",
    ),  # #264
    "wurmple": PaletteEntry(
        normal_hues=(0, 179),
        shiny_hues=(154, 168),
        description="H:178->159 (diff=19)",
    ),  # #265
    # 266 silcoon: insufficient colored pixels
    "beautifly": PaletteEntry(
        normal_hues=(10, 35),
        shiny_hues=(153, 166),
        description="H:30->158 (diff=52)",
    ),  # #267
    "cascoon": PaletteEntry(
        normal_hues=(130, 150),
        shiny_hues=(37, 53),
        description="H:135->42 (diff=87)",
    ),  # #268
    "dustox": PaletteEntry(
        normal_hues=(0, 168),
        shiny_hues=(0, 33),
        description="H:0->12 (diff=12)",
    ),  # #269
    "lotad": PaletteEntry(
        normal_hues=(43, 55),
        shiny_hues=(88, 102),
        description="H:50->93 (diff=43)",
    ),  # #270
    "lombre": PaletteEntry(
        normal_hues=(31, 60),
        shiny_hues=(88, 99),
        description="H:36->93 (diff=57)",
    ),  # #271
    "ludicolo": PaletteEntry(
        normal_hues=(8, 55),
        shiny_hues=(81, 99),
        description="H:30->86 (diff=56)",
    ),  # #272
    "seedot": PaletteEntry(
        normal_hues=(7, 46),
        shiny_hues=(5, 35),
        subtle=True,
        description="H:30->30 (diff=0)",
    ),  # #273
    "nuzleaf": PaletteEntry(
        normal_hues=(145, 170),
        shiny_hues=(0, 170),
        description="H:150->0 (diff=30)",
    ),  # #274
    "shiftry": PaletteEntry(
        normal_hues=(123, 133),
        shiny_hues=(3, 50),
        description="H:128->25 (diff=77)",
    ),  # #275
    "taillow": PaletteEntry(
        normal_hues=(108, 120),
        shiny_hues=(70, 86),
        description="H:113->75 (diff=38)",
    ),  # #276
    "swellow": PaletteEntry(
        normal_hues=(106, 120),
        shiny_hues=(70, 86),
        description="H:111->75 (diff=36)",
    ),  # #277
    "wingull": PaletteEntry(
        normal_hues=(104, 131),
        shiny_hues=(130, 142),
        description="H:126->137 (diff=11)",
    ),  # #278
    "pelipper": PaletteEntry(
        normal_hues=(6, 30),
        shiny_hues=(6, 30),
        subtle=True,
        description="H:22->25 (diff=3)",
    ),  # #279
    "ralts": PaletteEntry(
        normal_hues=(43, 75),
        shiny_hues=(88, 106),
        description="H:60->101 (diff=41)",
    ),  # #280
    "kirlia": PaletteEntry(
        normal_hues=(43, 75),
        shiny_hues=(88, 111),
        description="H:60->101 (diff=41)",
    ),  # #281
    "gardevoir": PaletteEntry(
        normal_hues=(43, 75),
        shiny_hues=(127, 148),
        description="H:60->143 (diff=83)",
    ),  # #282
    "surskit": PaletteEntry(
        normal_hues=(85, 109),
        shiny_hues=(105, 115),
        description="H:90->110 (diff=20)",
    ),  # #283
    "masquerain": PaletteEntry(
        normal_hues=(0, 22),
        shiny_hues=(5, 53),
        description="H:17->30 (diff=13)",
    ),  # #284
    "shroomish": PaletteEntry(
        normal_hues=(10, 26),
        shiny_hues=(0, 28),
        subtle=True,
        description="H:18->18 (diff=0)",
    ),  # #285
    "breloom": PaletteEntry(
        normal_hues=(0, 27),
        shiny_hues=(0, 28),
        description="H:18->4 (diff=14)",
    ),  # #286
    "slakoth": PaletteEntry(
        normal_hues=(7, 24),
        shiny_hues=(0, 173),
        description="H:19->168 (diff=31)",
    ),  # #287
    "vigoroth": PaletteEntry(
        normal_hues=(0, 175),
        shiny_hues=(8, 30),
        description="H:0->23 (diff=23)",
    ),  # #288
    "slaking": PaletteEntry(
        normal_hues=(7, 179),
        shiny_hues=(2, 28),
        subtle=True,
        description="H:15->23 (diff=8)",
    ),  # #289
    "nincada": PaletteEntry(
        normal_hues=(4, 28),
        shiny_hues=(4, 30),
        subtle=True,
        description="H:15->18 (diff=3)",
    ),  # #290
    "ninjask": PaletteEntry(
        normal_hues=(115, 125),
        shiny_hues=(0, 29),
        description="H:120->22 (diff=82)",
    ),  # #291
    "shedinja": PaletteEntry(
        normal_hues=(16, 32),
        shiny_hues=(9, 24),
        description="H:27->14 (diff=13)",
    ),  # #292
    "whismur": PaletteEntry(
        normal_hues=(150, 170),
        shiny_hues=(0, 179),
        description="H:158->171 (diff=13)",
    ),  # #293
    "loudred": PaletteEntry(
        normal_hues=(115, 129),
        shiny_hues=(153, 173),
        description="H:124->158 (diff=34)",
    ),  # #294
    "exploud": PaletteEntry(
        normal_hues=(115, 129),
        shiny_hues=(0, 178),
        description="H:124->173 (diff=49)",
    ),  # #295
    "makuhita": PaletteEntry(
        normal_hues=(10, 28),
        shiny_hues=(0, 28),
        subtle=True,
        description="H:22->21 (diff=1)",
    ),  # #296
    "hariyama": PaletteEntry(
        normal_hues=(4, 28),
        shiny_hues=(0, 178),
        description="H:9->173 (diff=16)",
    ),  # #297
    "azurill": PaletteEntry(
        normal_hues=(103, 118),
        shiny_hues=(55, 85),
        description="H:113->71 (diff=42)",
    ),  # #298
    "nosepass": PaletteEntry(
        normal_hues=(93, 125),
        shiny_hues=(1, 28),
        description="H:105->21 (diff=84)",
    ),  # #299
    "skitty": PaletteEntry(
        normal_hues=(0, 179),
        shiny_hues=(0, 28),
        subtle=True,
        description="H:5->5 (diff=0)",
    ),  # #300
    "delcatty": PaletteEntry(
        normal_hues=(8, 179),
        shiny_hues=(0, 29),
        description="H:173->7 (diff=14)",
    ),  # #301
    "sableye": PaletteEntry(
        normal_hues=(139, 158),
        shiny_hues=(5, 19),
        description="H:150->10 (diff=40)",
    ),  # #302
    "mawile": PaletteEntry(
        normal_hues=(13, 26),
        shiny_hues=(158, 170),
        description="H:20->165 (diff=35)",
    ),  # #303
    "aron": PaletteEntry(
        normal_hues=(98, 116),
        shiny_hues=(25, 35),
        description="H:103->30 (diff=73)",
    ),  # #304
    "lairon": PaletteEntry(
        normal_hues=(115, 125),
        shiny_hues=(81, 99),
        description="H:120->86 (diff=34)",
    ),  # #305
    "aggron": PaletteEntry(
        normal_hues=(0, 179),
        shiny_hues=(81, 99),
        description="H:0->86 (diff=86)",
    ),  # #306
    "meditite": PaletteEntry(
        normal_hues=(101, 113),
        shiny_hues=(0, 179),
        description="H:106->175 (diff=69)",
    ),  # #307
    "medicham": PaletteEntry(
        normal_hues=(0, 26),
        shiny_hues=(101, 113),
        description="H:2->108 (diff=74)",
    ),  # #308
    "electrike": PaletteEntry(
        normal_hues=(47, 72),
        shiny_hues=(98, 125),
        description="H:52->103 (diff=51)",
    ),  # #309
    "manectric": PaletteEntry(
        normal_hues=(18, 40),
        shiny_hues=(13, 28),
        subtle=True,
        description="H:32->23 (diff=9)",
    ),  # #310
    "plusle": PaletteEntry(
        normal_hues=(0, 29),
        shiny_hues=(0, 30),
        description="H:21->6 (diff=15)",
    ),  # #311
    "minun": PaletteEntry(
        normal_hues=(16, 29),
        shiny_hues=(81, 99),
        description="H:21->86 (diff=65)",
    ),  # #312
    "volbeat": PaletteEntry(
        normal_hues=(100, 118),
        shiny_hues=(135, 149),
        description="H:105->144 (diff=39)",
    ),  # #313
    "illumise": PaletteEntry(
        normal_hues=(138, 155),
        shiny_hues=(97, 109),
        description="H:143->102 (diff=41)",
    ),  # #314
    "roselia": PaletteEntry(
        normal_hues=(39, 58),
        shiny_hues=(19, 49),
        subtle=True,
        description="H:50->44 (diff=6)",
    ),  # #315
    "gulpin": PaletteEntry(
        normal_hues=(45, 58),
        shiny_hues=(98, 114),
        description="H:53->106 (diff=53)",
    ),  # #316
    "swalot": PaletteEntry(
        normal_hues=(128, 140),
        shiny_hues=(100, 120),
        description="H:133->105 (diff=28)",
    ),  # #317
    "carvanha": PaletteEntry(
        normal_hues=(0, 25),
        shiny_hues=(80, 90),
        description="H:0->85 (diff=85)",
    ),  # #318
    "sharpedo": PaletteEntry(
        normal_hues=(85, 110),
        shiny_hues=(148, 175),
        description="H:93->153 (diff=60)",
    ),  # #319
    "wailmer": PaletteEntry(
        normal_hues=(99, 113),
        shiny_hues=(130, 140),
        description="H:104->135 (diff=31)",
    ),  # #320
    "wailord": PaletteEntry(
        normal_hues=(100, 119),
        shiny_hues=(130, 155),
        description="H:113->135 (diff=22)",
    ),  # #321
    "numel": PaletteEntry(
        normal_hues=(20, 46),
        shiny_hues=(8, 35),
        description="H:27->15 (diff=12)",
    ),  # #322
    "camerupt": PaletteEntry(
        normal_hues=(7, 35),
        shiny_hues=(115, 140),
        description="H:30->135 (diff=75)",
    ),  # #323
    "torkoal": PaletteEntry(
        normal_hues=(0, 179),
        shiny_hues=(0, 23),
        subtle=True,
        description="H:10->10 (diff=0)",
    ),  # #324
    "spoink": PaletteEntry(
        normal_hues=(100, 110),
        shiny_hues=(3, 20),
        description="H:105->12 (diff=87)",
    ),  # #325
    "grumpig": PaletteEntry(
        normal_hues=(136, 172),
        shiny_hues=(19, 33),
        description="H:147->25 (diff=58)",
    ),  # #326
    "spinda": PaletteEntry(
        normal_hues=(6, 28),
        shiny_hues=(7, 40),
        subtle=True,
        description="H:23->23 (diff=0)",
    ),  # #327
    "trapinch": PaletteEntry(
        normal_hues=(0, 20),
        shiny_hues=(75, 89),
        description="H:15->84 (diff=69)",
    ),  # #328
    "vibrava": PaletteEntry(
        normal_hues=(68, 81),
        shiny_hues=(4, 31),
        description="H:75->9 (diff=66)",
    ),  # #329
    "flygon": PaletteEntry(
        normal_hues=(0, 5),
        shiny_hues=(96, 106),
        description="H:0->101 (diff=79)",
    ),  # #330
    "cacnea": PaletteEntry(
        normal_hues=(18, 60),
        shiny_hues=(4, 28),
        description="H:38->20 (diff=18)",
    ),  # #331
    "cacturne": PaletteEntry(
        normal_hues=(33, 53),
        shiny_hues=(0, 28),
        description="H:41->20 (diff=21)",
    ),  # #332
    "swablu": PaletteEntry(
        normal_hues=(95, 125),
        shiny_hues=(16, 31),
        description="H:120->21 (diff=81)",
    ),  # #333
    "altaria": PaletteEntry(
        normal_hues=(99, 115),
        shiny_hues=(13, 26),
        description="H:104->21 (diff=83)",
    ),  # #334
    "zangoose": PaletteEntry(
        normal_hues=(0, 179),
        shiny_hues=(97, 125),
        description="H:178->103 (diff=75)",
    ),  # #335
    "seviper": PaletteEntry(
        normal_hues=(0, 173),
        shiny_hues=(0, 173),
        subtle=True,
        description="H:0->0 (diff=0)",
    ),  # #336
    "lunatone": PaletteEntry(
        normal_hues=(10, 29),
        shiny_hues=(10, 29),
        subtle=True,
        description="H:20->20 (diff=0)",
    ),  # #337
    "solrock": PaletteEntry(
        normal_hues=(8, 30),
        shiny_hues=(0, 30),
        subtle=True,
        description="H:15->15 (diff=0)",
    ),  # #338
    "barboach": PaletteEntry(
        normal_hues=(97, 125),
        shiny_hues=(14, 33),
        description="H:114->21 (diff=87)",
    ),  # #339
    "whiscash": PaletteEntry(
        normal_hues=(93, 118),
        shiny_hues=(93, 116),
        subtle=True,
        description="H:113->110 (diff=3)",
    ),  # #340
    "corphish": PaletteEntry(
        normal_hues=(5, 30),
        shiny_hues=(0, 23),
        description="H:12->0 (diff=12)",
    ),  # #341
    "crawdaunt": PaletteEntry(
        normal_hues=(2, 30),
        shiny_hues=(5, 31),
        subtle=True,
        description="H:10->16 (diff=6)",
    ),  # #342
    "baltoy": PaletteEntry(
        normal_hues=(7, 38),
        shiny_hues=(20, 35),
        subtle=True,
        description="H:30->25 (diff=5)",
    ),  # #343
    "claydol": PaletteEntry(
        normal_hues=(6, 43),
        shiny_hues=(18, 43),
        subtle=True,
        description="H:30->30 (diff=0)",
    ),  # #344
    "lileep": PaletteEntry(
        normal_hues=(6, 28),
        shiny_hues=(74, 84),
        description="H:19->79 (diff=60)",
    ),  # #345
    "cradily": PaletteEntry(
        normal_hues=(48, 80),
        shiny_hues=(0, 179),
        description="H:57->170 (diff=67)",
    ),  # #346
    "anorith": PaletteEntry(
        normal_hues=(55, 65),
        shiny_hues=(115, 125),
        description="H:60->120 (diff=60)",
    ),  # #347
    "armaldo": PaletteEntry(
        normal_hues=(105, 125),
        shiny_hues=(0, 25),
        description="H:120->4 (diff=64)",
    ),  # #348
    "feebas": PaletteEntry(
        normal_hues=(10, 35),
        shiny_hues=(168, 178),
        description="H:30->173 (diff=37)",
    ),  # #349
    "milotic": PaletteEntry(
        normal_hues=(100, 110),
        shiny_hues=(111, 135),
        description="H:105->116 (diff=11)",
    ),  # #350
    # 351 castform: insufficient colored pixels
    "kecleon": PaletteEntry(
        normal_hues=(52, 77),
        shiny_hues=(52, 77),
        subtle=True,
        description="H:72->72 (diff=0)",
    ),  # #352
    "shuppet": PaletteEntry(
        normal_hues=(92, 105),
        shiny_hues=(88, 103),
        subtle=True,
        description="H:100->93 (diff=7)",
    ),  # #353
    "banette": PaletteEntry(
        normal_hues=(115, 125),
        shiny_hues=(94, 115),
        description="H:120->99 (diff=21)",
    ),  # #354
    "duskull": PaletteEntry(
        normal_hues=(20, 35),
        shiny_hues=(0, 30),
        description="H:30->5 (diff=25)",
    ),  # #355
    "dusclops": PaletteEntry(
        normal_hues=(3, 35),
        shiny_hues=(0, 20),
        description="H:15->5 (diff=10)",
    ),  # #356
    "tropius": PaletteEntry(
        normal_hues=(44, 70),
        shiny_hues=(16, 49),
        description="H:62->37 (diff=25)",
    ),  # #357
    "chimecho": PaletteEntry(
        normal_hues=(98, 119),
        shiny_hues=(43, 75),
        description="H:103->60 (diff=43)",
    ),  # #358
    "absol": PaletteEntry(
        normal_hues=(85, 95),
        shiny_hues=(0, 10),
        description="H:90->5 (diff=85)",
    ),  # #359
    "wynaut": PaletteEntry(
        normal_hues=(91, 107),
        shiny_hues=(147, 179),
        description="H:99->159 (diff=60)",
    ),  # #360
    "snorunt": PaletteEntry(
        normal_hues=(0, 30),
        shiny_hues=(88, 106),
        description="H:18->101 (diff=83)",
    ),  # #361
    "glalie": PaletteEntry(
        normal_hues=(104, 125),
        shiny_hues=(93, 105),
        description="H:120->100 (diff=20)",
    ),  # #362
    "spheal": PaletteEntry(
        normal_hues=(16, 28),
        shiny_hues=(16, 28),
        subtle=True,
        description="H:21->23 (diff=2)",
    ),  # #363
    "sealeo": PaletteEntry(
        normal_hues=(98, 125),
        shiny_hues=(129, 151),
        description="H:109->142 (diff=33)",
    ),  # #364
    "walrein": PaletteEntry(
        normal_hues=(100, 118),
        shiny_hues=(120, 151),
        description="H:105->142 (diff=37)",
    ),  # #365
    "clamperl": PaletteEntry(
        normal_hues=(93, 117),
        shiny_hues=(81, 117),
        subtle=True,
        description="H:112->105 (diff=7)",
    ),  # #366
    "huntail": PaletteEntry(
        normal_hues=(92, 105),
        shiny_hues=(55, 75),
        description="H:97->68 (diff=29)",
    ),  # #367
    "gorebyss": PaletteEntry(
        normal_hues=(0, 178),
        shiny_hues=(14, 32),
        description="H:168->20 (diff=32)",
    ),  # #368
    "relicanth": PaletteEntry(
        normal_hues=(3, 24),
        shiny_hues=(92, 102),
        description="H:8->97 (diff=89)",
    ),  # #369
    "luvdisc": PaletteEntry(
        normal_hues=(0, 25),
        shiny_hues=(5, 35),
        description="H:9->26 (diff=17)",
    ),  # #370
    "bagon": PaletteEntry(
        normal_hues=(115, 135),
        shiny_hues=(55, 71),
        description="H:120->60 (diff=60)",
    ),  # #371
    "shelgon": PaletteEntry(
        normal_hues=(10, 35),
        shiny_hues=(40, 60),
        description="H:30->45 (diff=15)",
    ),  # #372
    "salamence": PaletteEntry(
        normal_hues=(108, 125),
        shiny_hues=(55, 71),
        description="H:120->60 (diff=60)",
    ),  # #373
    "beldum": PaletteEntry(
        normal_hues=(97, 121),
        shiny_hues=(0, 179),
        description="H:110->16 (diff=86)",
    ),  # #374
    "metang": PaletteEntry(
        normal_hues=(97, 121),
        shiny_hues=(11, 24),
        description="H:110->17 (diff=87)",
    ),  # #375
    "metagross": PaletteEntry(
        normal_hues=(97, 121),
        shiny_hues=(11, 24),
        description="H:108->17 (diff=89)",
    ),  # #376
    "regirock": PaletteEntry(
        normal_hues=(7, 31),
        shiny_hues=(3, 22),
        description="H:23->12 (diff=11)",
    ),  # #377
    "regice": PaletteEntry(
        normal_hues=(100, 133),
        shiny_hues=(91, 110),
        description="H:116->97 (diff=19)",
    ),  # #378
    "registeel": PaletteEntry(
        normal_hues=(18, 35),
        shiny_hues=(70, 88),
        description="H:30->75 (diff=45)",
    ),  # #379
    "latias": PaletteEntry(
        normal_hues=(0, 179),
        shiny_hues=(4, 28),
        subtle=True,
        description="H:0->9 (diff=9)",
    ),  # #380
    "latios": PaletteEntry(
        normal_hues=(100, 121),
        shiny_hues=(75, 95),
        description="H:108->81 (diff=27)",
    ),  # #381
    "kyogre": PaletteEntry(
        normal_hues=(102, 121),
        shiny_hues=(145, 157),
        description="H:110->152 (diff=42)",
    ),  # #382
    "groudon": PaletteEntry(
        normal_hues=(0, 179),
        shiny_hues=(25, 35),
        description="H:173->30 (diff=37)",
    ),  # #383
    "rayquaza": PaletteEntry(
        normal_hues=(68, 86),
        shiny_hues=(10, 33),
        description="H:81->28 (diff=53)",
    ),  # #384
    "jirachi": PaletteEntry(
        normal_hues=(16, 33),
        shiny_hues=(0, 33),
        subtle=True,
        description="H:23->23 (diff=0)",
    ),  # #385
    "deoxys": PaletteEntry(
        normal_hues=(4, 16),
        shiny_hues=(6, 33),
        description="H:10->25 (diff=15)",
    ),  # #386
}

# ---------------------------------------------------------------------------
# Hand-calibrated overrides from actual game captures.
# These replace auto-generated entries that are inaccurate due to
# background interference or sprite extraction differences.
# ---------------------------------------------------------------------------
FRLG_PALETTE_DB["mewtwo"] = PaletteEntry(
    normal_hues=(125, 155),
    shiny_hues=(40, 85),
    min_sat=120,  # high sat needed to filter Cerulean Cave background (H~21-30)
    min_val=80,
    description="Purple tail/accents (H~139) -> green tail/accents (H~44-46)",
)


def get_palette(species: str) -> Optional[PaletteEntry]:
    """Look up the palette entry for a species (case-insensitive)."""
    return FRLG_PALETTE_DB.get(species.lower().replace(" ", "_").replace("-", "_"))


def classify_hue(species: str, dominant_hue: int) -> Optional[bool]:
    """
    Given the dominant hue from a battle frame, classify as shiny or not.
    Returns True (shiny), False (normal), or None (inconclusive).
    """
    entry = get_palette(species)
    if entry is None:
        return None

    in_normal = entry.normal_hues[0] <= dominant_hue <= entry.normal_hues[1]
    in_shiny = entry.shiny_hues[0] <= dominant_hue <= entry.shiny_hues[1]

    if in_shiny and not in_normal:
        if entry.subtle:
            return None  # too subtle, need sparkle confirmation
        return True
    if in_normal and not in_shiny:
        return False
    return None  # overlapping or out of range
